CREATE TABLE IF NOT EXISTS xianyu_api_credential_reset_operation (
    operation_key VARCHAR(128) NOT NULL PRIMARY KEY,
    status VARCHAR(16) NOT NULL,
    completed_time DATETIME NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='API 密钥全量重置操作门禁';
