-- ============================================================================
-- V1.52__seed_qa_digital_appliance.sql
-- ----------------------------------------------------------------------------
-- 闲鱼平台 AI 客服学习知识库种子数据：数码家电一级分类（digital_appliance）
-- ----------------------------------------------------------------------------
-- 目标：为"数码家电"一级分类下的 6 个二级分类各填充 30 条高价值 Q&A，共 180 条。
--
-- 二级分类清单：
--   1. digital_phone          - 手机（iPhone/华为/小米/三星/OPPO/vivo）
--   2. digital_computer       - 电脑平板（笔记本/台式机/平板/MacBook/联想/戴尔）
--   3. digital_camera         - 相机摄影（单反/微单/镜头/三脚架/GoPro）
--   4. digital_audio          - 音频设备（耳机/音响/麦克风/AirPods/蓝牙音箱）
--   5. digital_appliance_home - 家用电器（冰箱/洗衣机/空调/电视/微波炉/电饭煲）
--   6. digital_smart          - 智能设备（智能手表/手环/音箱/家居/平衡车）
--
-- 覆盖场景：型号咨询、成色、电池健康度、是否拆修、配件齐全、真假辨别、
--           保修、数据迁移、系统问题、价格谈判
--
-- 数据约束：
--   * score: 70-95
--   * tags: 3-5 个，逗号分隔
--   * source_summary: 一句话摘要
--   * answer: 200-500 字
--   * source_type: seed
--   * learn_batch_id: seed-v1.52
--   * content_hash: MD5(question + answer)，保证唯一
--   * vector_indexed: 1（向量索引开启）
--
-- 写入方式：INSERT ... SELECT ... JOIN ai_cs_kb_category c ON c.code = q.code
--           仅在分类存在且未删除时写入，幂等可重入。
--           通过 uk_learned_kb_hash 唯一索引避免重复插入。
-- ============================================================================
-- 注意：本脚本为仅追加（append-only）、非破坏性 DDL/DML，符合迁移脚本规范。
--       不修改已发布脚本，不删除任何已有数据。
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. digital_phone（手机）- 30 条
-- ----------------------------------------------------------------------------
INSERT IGNORE INTO ai_cs_learned_kb (
    category_id, question, answer, tags, source_summary,
    content_hash, score, review_status, enabled, vector_indexed,
    source_count, source_conv_ids, learn_batch_id, sensitive_filtered,
    source_type, deleted, created_time, updated_time
)
SELECT c.id, q.question, q.answer, q.tags, q.source_summary,
       MD5(CONCAT(q.question, q.answer)), q.score, 'approved', 1, 1,
       1, NULL, 'seed-v1.52', 1, 'seed', 0, NOW(), NOW()
FROM (
  SELECT 'digital_phone' AS code, '这台iPhone 13的电池健康度还有多少？续航怎么样？' AS question, '您好，这台iPhone 13当前电池健康度为89%，处于健康状态（80%以上均属正常使用范围）。我用了大约一年半，主要是日常社交和追剧，没有高强度游戏使用，所以电池损耗比较平缓。按照当前健康度，正常使用还能撑一天一充，重度使用可能需要中午补一次电。如果您对续航有较高要求，我可以帮您推荐同款128G版本，或者您可以等我下周到的一批电池健康度92%以上的机子。另外，更换原装电池费用约500元，第三方约200元，您可以根据需要决定。' AS answer, 'iPhone,电池健康度,续航,成色,二手' AS tags, 'iPhone 13电池健康度89%的咨询与续航说明' AS source_summary, 88 AS score
  UNION ALL SELECT 'digital_phone', '这台华为Mate50是否拆修过？怎么证明？', '您好，这台Mate50绝对没有拆修史，我可以用以下三点证明：第一，机身螺丝完好无拧痕，您可以收到货后用放大镜检查；第二，防水胶条完整，拆过的机器一般会破坏原厂胶；第三，我保留了原厂包装盒、发票和保修卡，华为官方售后可以查到维修记录为零。我自己是从华为商城首发买的，用了8个月想换Mate60，所以出。如果您不放心，可以走闲鱼验机服务，验机费30元由我承担。有任何问题随时联系我。' AS answer, '华为Mate50,拆修,验机,发票,保修' AS tags, '华为Mate50无拆修证明与验机建议' AS source_summary, 90 AS score
  UNION ALL SELECT 'digital_phone', '小米14的激活时间是？还在保修期吗？', '您好，这台小米14是2024年1月15日激活的，目前还在小米官方一年保修期内，到2025年1月14日到期。激活时间可以在小米商城-服务-我的设备中查询，也可以打小米客服400-100-5678报IMEI号查询。保修期内非人为损坏可以免费维修。我保留了电子发票，过户后保修不影响。机器成色9成新，无磕碰无划痕，128G版本，骁龙8 Gen3处理器，日常使用和游戏都很流畅。如果需要我可以提供激活截图和发票截图。' AS answer, '小米14,激活时间,保修期,IMEI,发票' AS tags, '小米14激活时间与保修状态查询' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_phone', '三星S23 Ultra支持双卡双待吗？卡槽是什么样的？', '您好，三星S23 Ultra国行版支持双卡双待，物理双nano-SIM卡槽，也可以用eSIM加物理卡组合。卡槽在机身顶部，取卡针垂直插入即可弹出。我手里这台是国行12加256G版本，双卡都测试过正常使用，移动联通电信都支持5G。如果您是港版或美版需要注意，港版是单物理卡加eSIM，美版是纯eSIM。建议您购买前确认自己的运营商和使用需求。机器无锁无欠费，随时可以插卡使用。' AS answer, '三星S23Ultra,双卡双待,卡槽,eSIM,国行' AS tags, '三星S23 Ultra双卡双待与卡槽说明' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_phone', '怎么辨别OPPO Find X6真伪？担心买到山寨机', '您好，辨别OPPO Find X6真伪有以下几个方法：第一，拨号盘输入星号06井查看IMEI，与包装盒、机身背面贴纸三处比对，必须一致；第二，登录OPPO官网服务查询页面，输入IMEI号可以查到激活时间和保修状态，正品都会有记录；第三，ColorOS系统设置-关于手机中可以看到完整型号和处理器信息，山寨机往往处理器不对；第四，正品屏幕显示效果细腻，色彩饱满，山寨机屏幕明显发虚发白。我手里这台是国行正品，原装配件齐全，支持任何方式验机。' AS answer, 'OPPO,真伪辨别,IMEI,验机,山寨机' AS tags, 'OPPO Find X6真伪辨别方法汇总' AS source_summary, 87 AS score
  UNION ALL SELECT 'digital_phone', '这台iPhone能iCloud解锁吗？激活锁关了吗？', '您好，这台iPhone是正常解锁状态，iCloud账号已经退出，激活锁已关闭，您可以登录自己的Apple ID正常使用。我提醒您，购买二手iPhone一定要确认iCloud已退出，否则可能买到丢失模式或ID锁机，那种机器基本无法使用。具体检查方法：设置-顶部Apple ID-退出登录，如果seller退出时需要输入密码，说明账号正常。我买的时候就是新机激活自己用的，没有欠款没有纠纷，过户完全没问题。' AS answer, 'iPhone,iCloud,激活锁,ID锁,二手' AS tags, 'iPhone iCloud解锁状态确认与避坑指南' AS source_summary, 89 AS score
  UNION ALL SELECT 'digital_phone', '国行和港版iPhone有什么区别？买哪个划算？', '您好，国行和港版iPhone主要区别：第一，国行支持双物理nano-SIM卡，港版是单物理卡加eSIM，国内运营商eSIM支持有限；第二，国行享受国内一年保修，港版需到Apple Store或找授权维修点；第三，港版不支持Apple Intelligence部分功能；第四，港版价格通常便宜300-500元。我个人建议，如果您在国内长期使用，选国行更省心；如果您经常往返港澳或有eSIM需求，港版更灵活。我手里这台是国行256G，双卡双待，适合国内用户。' AS answer, 'iPhone,国行,港版,双卡,保修' AS tags, '国行与港版iPhone差异对比与选购建议' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_phone', '这台手机支持5G吗？哪个运营商都能用？', '您好，这台手机支持5G，三大运营商的5G网络都可以使用。具体频段方面，移动n41和n79，联通n78，电信n78都有覆盖。我实测在市区移动5G下载速度可达500Mbps，联通电信也都能跑300Mbps以上。需要注意的是，5G功耗比4G高一些，续航会略短，如果不需要可以在设置中关闭5G使用4G。机器是无锁全网通版本，插卡即用，不需要任何设置。如果您所在地区5G覆盖一般，建议先用4G也完全够用。' AS answer, '5G,全网通,运营商,频段,无锁' AS tags, '手机5G支持与运营商兼容性说明' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_phone', '配件齐全吗？送什么？', '您好，配件齐全，原装都有：包装盒、说明书、卡针、Type-C数据线、20W充电头（如果是新版包装）、硅胶保护壳（赠品）、贴膜（已贴）。我额外送您一张原厂钢化膜和一根编织数据线作为小礼物。所有配件都是原厂正品，没有第三方替换。包装盒上的序列号与手机一致，可以扫码验证。如果您不需要配件只要裸机，我可以优惠50元。机器使用约半年，所有配件几乎全新，充电头插口无氧化痕迹。' AS answer, '配件,原装,充电器,贴膜,赠品' AS tags, '手机配件清单与赠品说明' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_phone', '保修期内吗？怎么保修？', '您好，这台手机2024年3月激活，目前还在官方保修期内，到2025年3月到期。保修期内非人为损坏（如屏幕花屏、主板故障、电池健康度低于80%）可以免费维修。保修方式：第一，到官方售后服务中心，全国都有，可以官网查询最近网点；第二，邮寄维修，官方寄出寄回都免费；第三，部分机型支持上门维修。我保留了电子发票，过户后保修不影响，只需要凭IMEI号即可保修。建议收到货后先到官方查一下保修状态。' AS answer, '保修期,官方售后,IMEI,发票,维修' AS tags, '手机保修期内保修流程说明' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_phone', '屏幕有划痕吗？贴膜能盖住吗？', '您好，屏幕有一条非常轻微的划痕，长约5mm，在屏幕右下角，需要对着光线才能看到，贴膜后完全盖住看不见。我用玻璃贴膜盖了一年多，最近换膜时才发现。屏幕没有死点、亮点、彩斑，触控灵敏，显示色彩正常。建议您购买后立即贴钢化膜，可以避免后续划伤。如果对成色要求极高，我手里还有一台9.9成新的同款，价格贵100元，几乎无任何使用痕迹，您可以考虑。' AS answer, '屏幕,划痕,贴膜,成色,钢化膜' AS tags, '屏幕轻微划痕与贴膜遮盖说明' AS source_summary, 78 AS score
  UNION ALL SELECT 'digital_phone', '怎么判断是不是拆机屏？怕买到换屏机', '您好，判断拆机屏有几个方法：第一，原装屏底部Home键或顶部听筒周围胶水均匀，拆机屏胶水会有不规则；第二，原装屏显示黑色纯净，拆机屏往往发灰或漏光；第三，原装屏触控灵敏均匀，拆机屏边缘可能不灵敏；第四，强光下原装屏有原厂疏油层水珠效应，拆机屏水珠会散开；第五，拆机后盖螺丝有无拧痕。我手里这台是原装屏，您可以收到货后用以上方法验证，也可以到官方售后检测，非原装我可以全额退款。' AS answer, '拆机屏,原装屏,验机,屏幕,翻新' AS tags, '拆机屏辨别方法与原装屏验证' AS source_summary, 88 AS score
  UNION ALL SELECT 'digital_phone', '手机进过水吗？怎么检测？', '您好，这台手机没有进过水。检测进水有几个方法：第一，iPhone的SIM卡槽内有液体接触指示器，正常是白色或银色，进水会变红色；第二，听筒和扬声器网孔有无水渍痕迹；第三，屏幕有无水雾、显示是否正常；第四，充电口有无腐蚀或白色氧化物；第五，面容ID或指纹是否正常工作（进水容易损坏）。我手里这台所有检测点都正常，指示器是白色，您收到货可以自行检查。建议日常使用避免带进浴室，虽然现在手机都有IP68防水，但防水不防蒸汽。' AS answer, '进水,防水,LCI,IP68,验机' AS tags, '手机进水检测方法与防水说明' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_phone', '旧手机数据怎么迁移到新手机？', '您好，数据迁移有几种方式：第一，iPhone之间用快速开始功能，两台手机放一起，按提示操作即可，通讯录、照片、APP、微信聊天记录都可以迁移，需要两台手机都连WiFi；第二，安卓到iPhone用转移到iOS应用，可以从安卓迁移通讯录、照片、短信等；第三，微信聊天记录需要在微信内迁移，我-设置-聊天-聊天记录迁移与备份；第四，重要照片建议同时备份到云盘或电脑。建议迁移前先备份一次，避免意外。迁移完成后旧手机记得退出账号并恢复出厂设置再出售。' AS answer, '数据迁移,iCloud,微信,备份,恢复出厂' AS tags, '旧手机数据迁移方法与备份建议' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_phone', '系统版本是多少？可以升级吗？', '您好，当前系统是iOS 17.4.1，可以正常升级到最新iOS 17.5。系统流畅无卡顿，所有功能正常。建议升级前先备份到iCloud或电脑，升级过程中保持电量50%以上或连接充电器。如果您想降级到旧版本，苹果只签名最近一两个版本，降级窗口有限。我个人建议保持最新版本，安全性更好，新功能也多。机器没有越狱，没有描述文件冲突，升级不会有任何问题。' AS answer, 'iOS,系统版本,升级,越狱,备份' AS tags, 'iOS系统版本与升级注意事项' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_phone', '价格还能便宜点吗？', '您好，这个价格我已经压得很低了，相比同款二手市场均价便宜200元左右。如果您诚心要，我可以再优惠50元，并赠送一张原厂钢化膜和一根数据线，这样下来比市场便宜300元了。您也知道闲鱼数码利润薄，主要走量。如果走验机服务，验机费30元我承担。如果您一次买两台（我和朋友还有一台同款），可以再优惠100元每台。已经是底价了，再低就亏本了，希望您理解。' AS answer, '价格,议价,优惠,验机,赠品' AS tags, '手机价格谈判与优惠方案' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_phone', '有发票吗？是电子发票还是纸质发票？', '您好，有电子发票，是购买时商家开具的增值税普通发票，发票抬头是我的名字，发票内容是手机型号和金额。电子发票可以在购买平台的订单详情中查看和下载，我会截图发您，也可以转发PDF文件。电子发票与纸质发票具有同等法律效力，可以用于保修和报销。如果您需要改抬头，我无法修改，但保修不需要抬头一致，凭IMEI号即可保修。如果您需要纸质发票，可以联系商家补开，但需要邮费到付。' AS answer, '发票,电子发票,保修,报销,IMEI' AS tags, '电子发票说明与保修凭证' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_phone', '原包装盒还在吗？序列号对得上吗？', '您好，原包装盒完好保留，盒子上的序列号、IMEI、型号与手机完全一致，您可以扫码或手动比对验证。包装盒上的封条已经拆开（因为用过），但盒子本身没有损坏。盒子内含说明书、卡针、贴纸等附件齐全。建议您收到货后第一时间核对包装盒序列号与手机设置-关于本机中的序列号，确认一致后再确认收货。如果序列号不一致，可能是翻新机或组装机，您可以申请退款。我手里这台所有信息一致，欢迎验机。' AS answer, '包装盒,序列号,IMEI,验机,翻新机' AS tags, '原包装盒与序列号核对验证' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_phone', '充电器是Type-C还是Lightning接口？', '您好，这款手机的充电接口是Type-C（如果是iPhone 15系列及以后）或Lightning（如果是iPhone 14及以前）。具体型号是iPhone 15，所以是Type-C接口，充电更方便，可以用iPad或Mac的Type-C线充电，也支持USB-PD快充，30分钟可充50%。原装充电头是20W Type-C接口，数据线是Type-C to Type-C。如果您之前的iPhone是Lightning接口，需要更换数据线和充电头。我手里这台配件齐全，可以直接使用。' AS answer, 'Type-C,Lightning,充电器,iPhone15,快充' AS tags, '充电接口类型与快充说明' AS source_summary, 79 AS score
  UNION ALL SELECT 'digital_phone', '信号怎么样？通话清晰吗？', '您好，信号良好，通话清晰。我日常使用移动卡，市区和郊区信号都满格，地下室和电梯内信号略弱但通话不断线。WiFi信号接收也比较强，隔一堵墙仍能稳定连接。通话质量清晰无杂音，对方也能清楚听到我说话。如果遇到信号问题，建议先检查SIM卡是否接触良好，或者尝试网络设置还原（设置-通用-还原-还原网络设置）。机器支持VoLTE高清通话，需要运营商开通。总体信号表现是同价位优秀水平。' AS answer, '信号,通话,WiFi,VoLTE,网络' AS tags, '手机信号与通话质量说明' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_phone', '摄像头有划痕吗？拍照效果怎么样？', '您好，摄像头镜片无划痕无磕碰，拍照效果优秀。后置三摄（主摄加超广角加长焦）都正常工作，对焦迅速，无紫点无黑斑。前置摄像头清晰，Face ID正常。我测试过夜景、人像、视频都很出色，与同款新机无差异。建议日常使用给手机戴保护壳，避免摄像头镜片直接接触桌面造成划痕。如果镜头内有灰尘，可能是密封圈老化，建议到官方售后清洁。我手里这台所有镜头完美，欢迎到货验机。' AS answer, '摄像头,拍照,镜片,FaceID,验机' AS tags, '摄像头成色与拍照效果说明' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_phone', 'Face ID和指纹解锁都正常吗？', '您好，Face ID和指纹解锁（如果是支持指纹的机型）都正常工作。Face ID识别迅速，戴口罩也可以解锁（需开启戴口罩使用Face ID），暗光环境下也能正常识别。指纹解锁灵敏，湿手可能识别率下降。建议设置Face ID时正对手机，多角度录入。如果Face ID失效，可能是原深感摄像头损坏，建议到官方售后维修。我手里这台所有生物识别功能正常，您到货后可以测试。机器没有拆修，Face ID没有被禁用。' AS answer, 'FaceID,指纹解锁,生物识别,暗光,口罩' AS tags, 'Face ID与指纹解锁功能测试' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_phone', '是128G还是256G？实际可用多少？', '您好，这台是256G版本，系统占用约15G，实际可用约241G。128G版本系统占用相同，可用约113G。日常使用建议：如果只装常用APP加少量照片视频，128G够用；如果喜欢拍照录像、装大量游戏，建议256G起步；如果是工作者需要存大量文件，可以考虑512G。我手里这台256G用了一年还剩180G，主要存了5000张照片和20个APP。256G相比128G贵200-300元，性价比更高，转手也更容易。' AS answer, '128G,256G,存储,容量,性价比' AS tags, '手机存储版本与实际可用空间' AS source_summary, 81 AS score
  UNION ALL SELECT 'digital_phone', '9成新和95新有什么区别？怎么定义？', '您好，闲鱼成色定义大致如下：全新未拆封等于全新；99新等于仅拆封未使用或使用1-2次无任何痕迹；95新等于使用少，无划痕无磕碰，功能完好；9新等于正常使用，有轻微划痕或磨损，功能正常；8新等于有明显使用痕迹，可能有磕碰；7新及以下等于成色较差。我手里这台是95新，使用半年，有原厂保护壳和贴膜，无任何划痕磕碰，功能全部正常。建议购买二手选择95新以上，性价比和成色平衡较好。低于9新的机器价格便宜，但需要接受明显使用痕迹。' AS answer, '成色,95新,9成新,定义,二手' AS tags, '闲鱼成色等级定义与选购建议' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_phone', '发什么快递？包邮吗？多久到？', '您好，默认发顺丰速运，包邮（偏远地区除外，新疆西藏需补邮费20元）。顺丰一般次日达，偏远地区2-3天。包装用原厂盒加气泡膜加顺丰专用纸箱，三层保护，确保运输无损。发货前会拍摄视频留证，包括机器成色、配件、序列号、包装过程。签收时建议您当面验货，确认无误后再签收，如有问题可以拒收并联系我。如果不接受顺丰到付，我也可以发中通圆通，邮费同样我承担。发货时间一般是付款后24小时内，节假日顺延。' AS answer, '顺丰,包邮,发货,验货,包装' AS tags, '快递发货与包装验货流程' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_phone', '支持验机服务吗？验机费谁出？', '您好，支持闲鱼验机服务，验机费30元由我承担。验机流程：您下单时选择验机服务，机器先发到闲鱼验机中心，专业工程师检测后出具报告，您确认无误再发货给您，有问题可以申请退款。验机内容包括：外观成色、屏幕显示、功能测试、拆修检测、进水检测、电池健康度等。验机报告具有权威性，可以作为交易凭证。建议购买二手数码都走验机，30元买个安心。如果验机发现问题，验机费不退（由我承担），但货款全额退还。' AS answer, '验机,验机费,闲鱼验机,检测,退款' AS tags, '闲鱼验机服务流程与费用说明' AS source_summary, 87 AS score
  UNION ALL SELECT 'digital_phone', '支持以旧换新吗？旧手机怎么估价？', '您好，支持以旧换新，旧手机估价您可以参考以下渠道：第一，闲鱼回收选机型填成色出价；第二，爱回收、回收宝等第三方回收平台；第三，苹果官网以旧换新（限国行iPhone）；第四，到当地数码城询价。建议多对比几个渠道，价高者出。旧手机估价主要看成色、电池健康度、是否拆修、是否进水、屏幕状况。如果您的旧手机成色较好，建议直接闲鱼零售，比回收价高200-500元。我手里这台不接受以旧换新抵扣，但可以指导您出售旧机。' AS answer, '以旧换新,估价,回收,爱回收,闲鱼回收' AS tags, '以旧换新估价渠道与建议' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_phone', '国行保修怎么查询？需要什么凭证？', '您好，国行iPhone保修查询方法：第一，登录苹果官网技术支持查看保修状态，输入序列号即可查询；第二，下载Apple Support应用，登录Apple ID后可以查看所有设备保修状态；第三，到Apple Store或授权维修点查询。保修凭证主要是序列号，不需要发票（但建议保留）。国行保修期从激活日起算1年，电池保修从激活日起算1年（健康度低于80%可免费更换）。主要部件（主板、屏幕）保修2年。我手里这台激活时间是2024年3月，目前所有保修都在期内。' AS answer, '国行,保修查询,序列号,AppleID,凭证' AS tags, '国行iPhone保修查询方法与凭证' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_phone', '手机发热严重吗？玩游戏会烫手吗？', '您好，这台手机日常使用温度正常，玩游戏会温热但不烫手。手机发热原因：高负载运行大型游戏或4K录制会产生热量；充电时发热属正常现象；环境温度高会加剧发热；手机壳影响散热，建议游戏时拆壳。发热严重排查：检查是否有异常耗电APP后台运行；关闭不必要的位置服务和后台刷新；更新到最新系统修复Bug；如果持续高温可能是电池或主板故障。我手里这台骁龙8 Gen3处理器，日常使用约35度，游戏约42度，属于正常范围。建议避免边充电边玩游戏，会增加发热和电池损耗。' AS answer, '发热,温度,游戏,散热,电池' AS tags, '手机发热原因与排查方法' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_phone', '手机能刷公交和门禁吗？NFC怎么用？', '您好，这台手机支持NFC，可以刷公交和门禁。NFC使用方法：公交卡方面，在钱包或小米公交APP中添加交通卡，支持全国200多个城市；充值后可以刷手机乘地铁公交；息屏状态下也可以刷卡，不需要解锁；支持快捷交通模式，不用亮屏直接刷。门禁卡方面，部分安卓手机可以复制实体门禁卡（小米、华为支持）；iPhone门禁卡功能受限，需要物业发卡支持；加密门禁卡可能无法复制。我手里这台是安卓手机，支持门禁卡复制和公交卡。NFC还可以用于支付（银联闪付、支付宝）和数据传输。机器9成新，NFC功能正常。' AS answer, 'NFC,公交卡,门禁卡,支付,刷卡' AS tags, '手机NFC公交与门禁使用' AS source_summary, 83 AS score
) q
JOIN ai_cs_kb_category c ON c.code = q.code AND c.deleted = 0 AND c.parent_id IS NOT NULL;


-- ----------------------------------------------------------------------------
-- 2. digital_computer（电脑平板）- 30 条
-- ----------------------------------------------------------------------------
INSERT IGNORE INTO ai_cs_learned_kb (
    category_id, question, answer, tags, source_summary,
    content_hash, score, review_status, enabled, vector_indexed,
    source_count, source_conv_ids, learn_batch_id, sensitive_filtered,
    source_type, deleted, created_time, updated_time
)
SELECT c.id, q.question, q.answer, q.tags, q.source_summary,
       MD5(CONCAT(q.question, q.answer)), q.score, 'approved', 1, 1,
       1, NULL, 'seed-v1.52', 1, 'seed', 0, NOW(), NOW()
FROM (
  SELECT 'digital_computer' AS code, '这台MacBook Pro M2是几寸的？配置怎么样？' AS question, '您好，这台是MacBook Pro 14寸 M2 Pro芯片版本，配置是10核CPU加16核GPU，16G统一内存，512G固态硬盘。M2 Pro性能强劲，可以流畅运行Final Cut Pro剪辑4K视频、Logic Pro音乐制作、Xcode开发等专业软件。屏幕是Liquid Retina XDR，色彩精准，适合设计师和视频工作者。电池续航约18小时，日常办公一天不用充电。机器2023年6月购买，使用半年，成色95新，无划痕无磕碰。原包装盒和充电器齐全，国行正品。' AS answer, 'MacBookPro,M2,配置,14寸,国行' AS tags, 'MacBook Pro M2配置参数说明' AS source_summary, 90 AS score
  UNION ALL SELECT 'digital_computer', '联想ThinkPad X1 Carbon能跑大型软件吗？性能够用吗？', '您好，这台ThinkPad X1 Carbon是2023款，i7-1365U处理器，16G内存，512G固态，适合办公和轻度设计。跑Office、浏览器、PS修图、写代码完全没问题。但跑大型3D渲染、AE特效、大型游戏会比较吃力，毕竟是轻薄本不是游戏本。如果您主要是办公出差用，X1 Carbon非常合适，1.12kg很轻便，键盘手感是笔记本里最好的之一。续航约10小时，支持快充。机器9成新，有轻微使用痕迹，功能全部正常，原装电源适配器齐全。' AS answer, 'ThinkPad,X1Carbon,性能,办公,轻薄本' AS tags, 'ThinkPad X1 Carbon性能与适用场景' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_computer', '戴尔XPS 15的屏幕是4K的吗？色彩怎么样？', '您好，这台戴尔XPS 15是4K OLED触控屏版本，分辨率3840x2400，100% DCI-P3色域，500尼特亮度。屏幕色彩非常出色，适合摄影师和设计师使用，出厂经过校色，Delta E小于2。OLED屏幕黑色纯净，对比度极高，看视频也很享受。需要注意的是4K屏比1080p费电，续航约6-7小时。机器配置i7-12700H加RTX 3050 Ti，可以跑PR、AE等创作软件。9成新，无坏点无漏光，原装包装盒和电源齐全。' AS answer, '戴尔XPS15,4K,OLED,屏幕,色域' AS tags, '戴尔XPS 15 4K屏幕色彩说明' AS source_summary, 88 AS score
  UNION ALL SELECT 'digital_computer', 'iPad Pro能完全替代电脑吗？能跑PS和PR吗？', '您好，iPad Pro可以部分替代电脑，但要看您的使用场景。能做的：文字处理（Pages、Word）、邮件、浏览网页、看视频、记笔记（GoodNotes）、画图（Procreate）、简单修图（Lightroom）。不能做的：完整版Photoshop和Premiere（只有阉割版）、专业3D建模、大型PC游戏、多窗口高效办公。如果您是学生或轻度办公，iPad Pro加妙控键盘可以替代电脑；如果您是专业设计师或视频剪辑师，还是需要电脑。我手里这台是iPad Pro 12.9寸 M2芯片，256G，成色95新。' AS answer, 'iPadPro,替代电脑,PS,PR,M2' AS tags, 'iPad Pro能否替代电脑分析' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_computer', '华为MateBook 14的电池续航怎么样？能用多久？' AS question, '您好，华为MateBook 14电池容量56Wh，官方标称续航11小时。实际使用：办公文档约8-9小时，看视频约7小时，高强度使用约5小时。支持65W快充，30分钟可充50%。电池健康度约95%，使用一年左右，损耗很小。续航表现中规中矩，比MacBook Air差一些但比同价位Windows本好。如果您经常出差，建议带充电器。机器9成新，无拆修，电池循环次数约80次。配置i5-1340P加16G加512G，日常办公和轻度设计完全够用。' AS answer, '华为MateBook,电池续航,快充,循环次数,办公' AS tags, '华为MateBook 14电池续航说明' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_computer', '华硕ROG游戏本散热怎么样？玩游戏会降频吗？', '您好，这台华硕ROG枪神7 Plus，i9-13980HX加RTX 4070，散热非常强。采用液金导热加双风扇三出风口，玩赛博朋克2077高画质2小时，CPU温度约85度，GPU约78度，没有明显降频。风扇噪音约50分贝，戴耳机基本听不到。日常办公浏览网页风扇基本不转，很安静。建议游戏时垫高底部增加进风量，或者接散热底座。机器9成新，散热模块无拆修，硅脂和液金原厂状态。玩3A大作毫无压力，电竞游戏帧数稳定。' AS answer, '华硕ROG,散热,游戏,降频,液金' AS tags, '华硕ROG游戏本散热性能测试' AS source_summary, 89 AS score
  UNION ALL SELECT 'digital_computer', '惠普暗影精灵9风扇噪音大吗？办公室用合适吗？', '您好，惠普暗影精灵9风扇噪音控制还可以。日常办公浏览网页风扇几乎不转，噪音约30分贝，很安静。中度负载（多开网页、轻度PS）风扇低转速，噪音约38分贝，办公室可以接受。高负载（游戏、渲染）风扇全速，噪音约48分贝，办公室会比较明显。如果您主要在办公室用，建议选安静模式（OMEN Gaming Hub里设置），性能会降低但噪音控制在35分贝以内。机器9成新，i7-13700HX加RTX 4060，游戏和办公都适合。' AS answer, '惠普暗影精灵,风扇噪音,办公,散热,游戏' AS tags, '惠普暗影精灵9风扇噪音评估' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_computer', 'MacBook Air M2 8G内存够用吗？会卡顿吗？', '您好，MacBook Air M2 8G内存是否够用取决于使用场景。够用的场景：日常办公（Office、邮件、浏览器开10个标签）、看视频、轻度修图、写文档。不够用的场景：同时开多个大型软件（PS加PR加浏览器）、4K视频剪辑、3D建模、虚拟机。8G是macOS的起步内存，日常使用流畅，但多任务会触发swap（虚拟内存），长期可能增加硬盘损耗。如果您预算允许，建议加1500元升级到16G，用3-5年更从容。我手里这台8G版使用半年，日常办公无卡顿。' AS answer, 'MacBookAir,M2,8G内存,卡顿,升级' AS tags, 'MacBook Air M2 8G内存够用分析' AS source_summary, 87 AS score
  UNION ALL SELECT 'digital_computer', '联想小新Pro 16键盘手感怎么样？适合打字吗？', '您好，联想小新Pro 16键盘手感不错，1.5mm键程，回弹有力，反馈清晰，适合长时间打字。背光键盘三档可调，暗光环境下也能看清键位。键盘布局合理，有数字小键盘，财务和数据处理很方便。按键声音适中，办公室使用不会吵到别人。我每天用这台电脑写代码约6小时，手指不累。机器9成新，键盘无油光无打油，所有按键灵敏。配置R7-7840H加16G加1T，性能也很强，性价比很高。' AS answer, '联想小新,键盘手感,打字,背光,数字键盘' AS tags, '联想小新Pro 16键盘手感评测' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_computer', '戴尔G15的显卡是RTX 4060吗？能玩什么游戏？', '您好，这台戴尔G15是RTX 4060版本，6G显存，可以流畅运行市面上绝大多数游戏。能玩的：英雄联盟、CS2、Valorant等电竞游戏高画质200帧以上；原神、永劫无间高画质100帧以上；赛博朋克2077、荒野大镖客2中高画质60帧；3A大作中画质基本都能60帧流畅。RTX 4060支持DLSS 3，开启后帧数提升明显。机器9成新，i7-13650HX加16G加512G，游戏性能强。建议加一根16G内存组双通道，游戏帧数还能提升10%。' AS answer, '戴尔G15,RTX4060,游戏,DLSS,帧数' AS tags, '戴尔G15 RTX 4060游戏性能说明' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_computer', 'iPad Air 5是M1芯片吗？和iPad Pro有什么区别？', '您好，iPad Air 5是M1芯片，性能很强。和iPad Pro的主要区别：第一，屏幕：Air是10.9寸Liquid Retina非全贴合，Pro是11寸或12.9寸ProMotion 120Hz（12.9寸是OLED或miniLED）；第二，摄像头：Air只有后置单摄，Pro有双摄加激光雷达；第三，接口：Air是USB-C 5Gbps，Pro是Thunderbolt 40Gbps；第四，扬声器：Air是双扬声器，Pro是四扬声器；第五，Face ID：Air是指纹识别电源键，Pro是Face ID。如果主要画画记笔记，Air性价比更高。' AS answer, 'iPadAir5,M1,iPadPro,区别,选购' AS tags, 'iPad Air 5与iPad Pro差异对比' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_computer', '微星游戏本GE66的RGB灯效怎么样？能自定义吗？', '您好，微星GE66的RGB灯效非常炫酷，采用SteelSeries单键RGB背光键盘，每个按键都可以单独设置颜色和效果。通过SteelSeries GG软件可以自定义：静态颜色、呼吸、波浪、反应、音频可视化等多种效果。灯效亮度三档可调，也可以关闭。键盘手感也不错，1.5mm键程，适合游戏和打字。机器9成新，i7-12800HX加RTX 3070 Ti，游戏性能强。所有按键灯效正常，无坏键。如果您喜欢RGB灯效，这台机器很适合，电竞氛围拉满。' AS answer, '微星GE66,RGB,灯效,SteelSeries,自定义' AS tags, '微星GE66 RGB灯效与自定义说明' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_computer', '这台MacBook有拆修过吗？怎么判断？', '您好，这台MacBook绝对没有拆修过。判断MacBook是否拆修的方法：第一，底部螺丝是原厂五角螺丝，无拧痕，拆过的会有划痕或换成十字螺丝；第二，屏幕转轴阻尼均匀，拆过的可能阻尼变化；第三，序列号在苹果官网查询维修记录；第四，底部脚垫平整，拆过的可能脚垫变形；第五，到Apple Store或授权维修点检测。我保留了原厂包装盒、发票和保修卡，序列号可以在苹果官网查询到保修状态。机器9成新，所有原厂螺丝完好，欢迎验机。' AS answer, 'MacBook,拆修,螺丝,序列号,验机' AS tags, 'MacBook拆修判断方法与验机' AS source_summary, 88 AS score
  UNION ALL SELECT 'digital_computer', '笔记本屏幕有坏点吗？怎么检测？', '您好，这台笔记本屏幕无坏点无亮点。检测坏点方法：第一，下载坏点检测软件（如IsmyLcdOK），显示纯红纯绿纯蓝纯白纯黑五种颜色，仔细观察是否有异常点；第二，白色背景下看是否有黑色点（暗点），黑色背景下看是否有白色或彩色点（亮点）；第三，全屏显示纯色图片检查。国家三包标准是3个坏点以内属于正常，但我手里这台一个都没有。屏幕无漏光无彩斑无竖线，显示色彩正常。建议到货后第一时间检测，有问题可以申请退款。机器9成新，屏幕完美。' AS answer, '屏幕,坏点,亮点,检测,三包' AS tags, '笔记本屏幕坏点检测方法' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_computer', 'ThinkPad的键盘进过水吗？按键都正常吗？', '您好，这台ThinkPad键盘没有进过水，所有按键正常。ThinkPad有防泼溅设计，键盘底部有排水孔，少量液体泼溅不会损坏主板。但进水后应立即关机、倒置晾干，不要尝试开机。判断进水方法：第一，键盘底部有无水渍痕迹；第二，按键手感是否一致（进水可能粘连）；第三，主板有无腐蚀痕迹。我手里这台所有按键回弹有力，无粘连无卡键，键盘灯正常。机器9成新，键盘无打油无磨损，小红点也正常。建议日常使用远离液体，虽然防泼溅但不防大量进水。' AS answer, 'ThinkPad,键盘,进水,防泼溅,按键' AS tags, 'ThinkPad键盘进水检测与说明' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_computer', '电脑能自己升级内存和硬盘吗？', '您好，这台电脑内存是板载的，无法自行升级，购买时就要选好容量。硬盘可以升级，M.2接口，支持NVMe SSD，最大支持2T。建议升级硬盘前先备份重要数据，然后到正规维修店更换，自己拆机有风险。内存升级方面，如果您买的是8G版本觉得不够用，只能换电脑，所以购买前一定要想清楚。我个人建议Windows本选16G起步，如果是创作或开发用途选32G。MacBook也是内存板载不可升级，购买时建议选16G。机器9成新，原装配置未改动。' AS answer, '内存,硬盘,升级,M.2,板载' AS tags, '电脑内存硬盘升级可行性' AS source_summary, 81 AS score
  UNION ALL SELECT 'digital_computer', '系统是正版的吗？带什么系统？', '您好，这台电脑是正版Windows 11家庭版，系统已激活，可以正常更新和使用所有功能。Windows 11相比Windows 10主要变化：界面更现代，开始菜单居中；支持Android应用（通过亚马逊应用商店）；更好的多任务管理（Snap Layouts）；改进的触控体验。如果您需要专业版（BitLocker加密、远程桌面等），可以自己升级。机器还预装了Office家庭和学生版（Word、Excel、PowerPoint），已激活可以正常使用。系统流畅无卡顿，无流氓软件。' AS answer, 'Windows11,正版,系统,激活,Office' AS tags, '电脑系统版本与正版授权说明' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_computer', '能跑Premiere Pro和After Effects吗？剪辑视频流畅吗？', '您好，这台电脑配置i7-12700H加RTX 3060加16G，跑PR和AE完全没问题。PR剪辑4K视频可以实时预览，加特效后可能需要代理。AE做2D动画和文字特效流畅，复杂3D场景可能卡顿。建议：剪辑时关闭其他大型软件；PR中开启GPU加速；素材放在SSD上速度更快；16G内存够用但建议32G更从容；定期清理缓存。RTX 3060的6G显存对4K剪辑足够，8K可能吃力。机器9成新，散热正常，长时间渲染不降频。如果您是专业剪辑师，建议考虑32G内存版本。' AS answer, 'PR,AE,剪辑,4K,GPU加速' AS tags, '电脑运行PR和AE性能评估' AS source_summary, 87 AS score
  UNION ALL SELECT 'digital_computer', '接口都有哪些？够用吗？', '您好，这台电脑接口齐全：左侧2个Thunderbolt 4（支持充电和数据传输）、1个HDMI 2.1、1个USB-A 3.2、1个3.5mm耳机口；右侧1个USB-A 3.2、1个SD卡槽。接口非常丰富，不需要扩展坞。Thunderbolt 4可以外接显示器、硬盘、显卡扩展坞。HDMI 2.1支持4K 120Hz输出。SD卡槽对摄影师很友好，直接读相机卡。如果您需要更多接口（网线、VGA等），可以买一个Type-C扩展坞。机器9成新，所有接口测试正常，无松动无接触不良。' AS answer, '接口,Thunderbolt,HDMI,USB,SD卡' AS tags, '电脑接口配置与扩展说明' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_computer', '有发票和保修卡吗？保修期到什么时候？', '您好，有电子发票和保修卡。电子发票是购买时开具的增值税普通发票，可以用于保修和报销。保修期从购买日起算2年（主要部件），电池1年。保修方式：到戴尔授权维修点，凭服务编码或发票即可保修。也可以拨打戴尔客服电话预约上门维修（部分机型支持）。我保留了购买凭证和原包装盒，过户后保修不影响。机器2023年6月购买，目前保修到2025年6月。建议到货后到戴尔官网输入服务编码查询保修状态确认。' AS answer, '发票,保修卡,戴尔,服务编码,保修期' AS tags, '电脑发票保修凭证说明' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_computer', '价格还能优惠吗？送什么东西？', '您好，这个价格已经是底价了，相比同款二手市场便宜300元左右。如果您诚心要，我可以再优惠100元，并赠送以下配件：第一，原装电脑包一个（价值150元）；第二，无线鼠标一个（价值80元）；第三，键盘保护膜一张；第四，屏幕贴膜一张。这样下来比市场便宜500元了。您也知道闲鱼数码利润薄，主要走量。如果走验机服务，验机费50元我承担。已经是底价了，再低就亏本了，希望您理解。机器9成新，性价比很高。' AS answer, '价格,优惠,赠品,电脑包,验机' AS tags, '电脑价格谈判与赠品方案' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_computer', '旧电脑数据怎么迁移？', '您好，数据迁移有几种方式：第一，Windows之间可以用外接硬盘或U盘拷贝，大文件可以用网线直连两台电脑传输速度快；第二，使用OneDrive或百度网盘云端同步；第三，浏览器书签可以登录账号同步；第四，微信聊天记录需要在微信内迁移（微信设置-通用-聊天记录迁移与备份）；第五，软件需要重新安装，不能直接拷贝。建议迁移前先整理重要文件，列出需要迁移的内容清单。迁移完成后旧电脑记得退出所有账号、恢复出厂设置、删除个人数据再出售。' AS answer, '数据迁移,外接硬盘,网盘,微信,备份' AS tags, '电脑数据迁移方法与建议' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_computer', '国行和水货笔记本有什么区别？', '您好，国行和水货笔记本主要区别：第一，保修：国行全国联保2年，水货需要找卖家或第三方维修；第二，键盘：国行有中文印刷，水货可能是英文或日文键盘；第三，电源适配器：国行是国标插头，水货可能需要转接头；第四，系统语言：国行预装中文系统，水货可能需要自己设置；第五，价格：水货通常便宜500-1500元。我个人建议买国行，保修方便，差价不大。如果您预算紧张且不介意保修，水货性价比高。我手里这台是国行正品，全国联保，发票齐全。' AS answer, '国行,水货,保修,键盘,电源' AS tags, '国行与水货笔记本差异对比' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_computer', '9成新的电脑使用多久了？电池损耗多少？', '您好，这台电脑使用约8个月，9成新。电池循环次数约120次，健康度约96%，损耗很小。正常使用每天充放电一次，一年循环约300次，电池健康度保持80%以上都属于正常。电池续航：官方标称10小时，实际办公约7-8小时，看视频约6小时。建议电池使用：避免完全放电再充电，20%以上就充电；不用时保持50%电量存放；避免高温环境使用；开启省电模式延长续航。机器9成新，电池性能良好，不需要更换。' AS answer, '9成新,电池损耗,循环次数,健康度,续航' AS tags, '电脑成色与电池损耗说明' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_computer', '支持验机吗？怎么验？', '您好，支持验机。验机方式：第一，闲鱼验机服务，下单时选择，机器发到验机中心检测，验机费50元由我承担；第二，您当地有懂电脑的朋友，可以带电脑到朋友店里检测；第三，到品牌官方售后检测（戴尔、联想等都有免费检测服务）；第四，自行检测，用鲁大师、CPU-Z、GPU-Z等软件查看配置和硬件信息。验机内容：配置是否与描述一致、屏幕有无坏点、硬盘通电时间、电池循环次数、接口是否正常、散热是否正常。机器9成新，欢迎任何方式验机，有问题全额退款。' AS answer, '验机,鲁大师,配置,检测,售后' AS tags, '电脑验机方式与检测内容' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_computer', '能跑AutoCAD和3D建模吗？', '您好，这台电脑i7-12700H加RTX 3060加16G，跑AutoCAD完全没问题，2D制图和3D建模都很流畅。能跑的软件：AutoCAD 2024、SolidWorks、SketchUp、Rhino、Blender等。3D建模复杂场景可能需要降低预览精度。渲染方面，RTX 3060支持GPU加速，渲染速度比纯CPU快很多。建议：16G内存够用但32G更从容；SSD硬盘提升加载速度；外接显示器提升工作效率。机器9成新，散热正常，长时间建模不卡顿。如果您是专业设计师，这台电脑完全够用。' AS answer, 'AutoCAD,3D建模,SolidWorks,渲染,GPU' AS tags, '电脑运行CAD和3D建模性能' AS source_summary, 87 AS score
  UNION ALL SELECT 'digital_computer', '屏幕是120Hz高刷吗？和60Hz区别大吗？', '您好，这台电脑屏幕是165Hz高刷屏，比60Hz流畅很多。区别：第一，日常操作（滚动网页、拖动窗口）更顺滑，没有拖影；第二，游戏帧数高时画面更流畅，电竞游戏（CS2、Valorant）高刷屏有明显优势；第三，看高帧率视频更流畅；第四，长时间使用眼睛更舒适，减少疲劳。如果您主要办公看视频，60Hz够用；如果玩游戏或对流畅度敏感，建议选高刷屏。机器9成新，屏幕无坏点无拖影，色彩正常。高刷屏是这代游戏本的标配，体验提升明显。' AS answer, '高刷屏,120Hz,165Hz,游戏,流畅度' AS tags, '高刷屏与60Hz区别说明' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_computer', '电脑能装黑苹果吗？兼容性怎么样？', '您好，这台电脑可以装黑苹果，但我不建议。原因：第一，黑苹果安装复杂，需要配置EFI和驱动，普通用户很难搞定；第二，兼容性问题多，可能WiFi、蓝牙、触控板、睡眠等功能不正常；第三，升级macOS后可能无法启动，需要重新配置；第四，违反苹果使用协议。如果您需要用macOS，建议直接买MacBook，体验好很多，二手MacBook Air M1约3500元，性价比很高。我手里这台Windows本9成新，适合Windows用户。装黑苹果风险自担，不建议尝试。' AS answer, '黑苹果,macOS,兼容性,驱动,MacBook' AS tags, '电脑装黑苹果可行性建议' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_computer', '包装箱和所有配件都在吗？', '您好，原包装箱和所有配件齐全：包装箱、说明书、电源适配器、电源线、保修卡、驱动U盘（部分品牌有）。包装箱上的序列号与电脑底部序列号一致，可以核对。电源适配器是原装20W Type-C（或65W），线材无破损。所有配件几乎全新，无使用痕迹。如果您不需要包装箱和配件，只要裸机，我可以优惠100元。建议保留包装箱，以后转手或保修时可能用到。机器9成新，配件齐全，欢迎核对。' AS answer, '包装箱,配件,电源适配器,序列号,保修卡' AS tags, '电脑包装箱与配件清单' AS source_summary, 81 AS score
  UNION ALL SELECT 'digital_computer', '能跑虚拟机和Docker吗？开发用够吗？', '您好，这台电脑i7-12700H加16G加512G，跑虚拟机和Docker完全没问题。能跑的：VMware、VirtualBox、Docker Desktop、WSL2等。建议：16G内存跑2-3个虚拟机够用，如果同时开多个建议升级到32G；Docker建议用WSL2后端，性能比Hyper-V好；SSD硬盘提升虚拟机读写速度；开启虚拟化需要在BIOS中设置。机器9成新，日常开发流畅。如果您是后端开发或运维，这台电脑配置够用。前端开发、Java开发、Python开发都完全没问题。' AS answer, '虚拟机,Docker,WSL2,开发,内存' AS tags, '电脑运行虚拟机和Docker能力' AS source_summary, 86 AS score
) q
JOIN ai_cs_kb_category c ON c.code = q.code AND c.deleted = 0 AND c.parent_id IS NOT NULL;


-- ----------------------------------------------------------------------------
-- 3. digital_camera（相机摄影）- 30 条
-- ----------------------------------------------------------------------------
INSERT IGNORE INTO ai_cs_learned_kb (
    category_id, question, answer, tags, source_summary,
    content_hash, score, review_status, enabled, vector_indexed,
    source_count, source_conv_ids, learn_batch_id, sensitive_filtered,
    source_type, deleted, created_time, updated_time
)
SELECT c.id, q.question, q.answer, q.tags, q.source_summary,
       MD5(CONCAT(q.question, q.answer)), q.score, 'approved', 1, 1,
       1, NULL, 'seed-v1.52', 1, 'seed', 0, NOW(), NOW()
FROM (
  SELECT 'digital_camera' AS code, '这台索尼A7M4快门次数多少？' AS question, '您好，这台索尼A7M4快门次数约8500次，属于很新的状态。A7M4官方标称快门寿命50万次，目前使用不到2%，还有很多年使用寿命。快门次数查询方法：用索尼官方软件 Imaging Edge 查看EXIF信息，或者用在线工具上传照片查看。我主要是周末拍人像和风景，不是商业拍摄，所以快门次数少。机器9成新，外观无磕碰无划痕，所有按键灵敏，拨轮阻尼正常。CMOS无灰尘无坏点，欢迎到货验机。原包装盒和配件齐全。' AS answer, '索尼A7M4,快门次数,寿命,EXIF,成色' AS tags, '索尼A7M4快门次数与寿命说明' AS source_summary, 90 AS score
  UNION ALL SELECT 'digital_camera', '佳能R6 Mark II是全画幅吗？和R6一代有什么区别？', '您好，佳能R6 Mark II是全画幅微单，2420万像素。和R6一代主要区别：第一，像素从2010万提升到2420万；第二，连拍速度从20fps提升到40fps（电子快门）；第三，视频从4K 60p提升到4K 60p无裁切；第四，新增10位HEIF照片格式；第五，对焦性能提升，支持识别马、火车等；第六，机身散热改进，长时间录制不过热。如果您拍运动或野生动物，R6II的40fps连拍很有优势。机器9成新，快门次数约5000次，国行正品，发票齐全。' AS answer, '佳能R6II,全画幅,连拍,像素,区别' AS tags, '佳能R6 Mark II与一代区别' AS source_summary, 88 AS score
  UNION ALL SELECT 'digital_camera', '尼康Z6 II的卡口是什么？能转接F卡口镜头吗？', '您好，尼康Z6 II是Z卡口（尼康微单卡口），可以通过FTZ转接环使用F卡口单反镜头。转接后：第一，原生Z卡口镜头支持自动对焦、防抖、EXIF信息传输；第二，F卡口镜头通过FTZ转接后，大部分镜头支持自动对焦（AF-S、AF-P镜头），老款AF镜头可能只能手动对焦；第三，转接后不影响画质，只是增加了一点长度和重量。我手里这台Z6II是机身，不含镜头，如果您有尼康单反镜头可以配FTZ转接环使用。机器9成新，卡口无磨损，触点干净。' AS answer, '尼康Z6II,Z卡口,F卡口,FTZ,转接' AS tags, '尼康Z6 II卡口与转接说明' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_camera', '富士XT5的胶片模拟效果怎么样？有哪几个模式？', '您好，富士XT5的胶片模拟是富士相机的特色，效果非常出色。XT5有19种胶片模拟模式，包括：Classic Chrome（经典负片，适合街头摄影）、Velvia（鲜艳，适合风景）、Provia（标准）、Astia（柔和）、Classic Neg（经典负片，复古色调）、Nostalgic Neg（怀旧负片）、Acros（黑白）等。胶片模拟直出效果很好，不需要后期调色，适合不喜欢后期处理的用户。XT5的4000万像素画质细腻，色彩还原准确。机器9成新，快门次数约3000次，国行正品。' AS answer, '富士XT5,胶片模拟,Classic Chrome,Velvia,直出' AS tags, '富士XT5胶片模拟模式说明' AS source_summary, 89 AS score
  UNION ALL SELECT 'digital_camera', '镜头有霉斑吗？怎么检查？', '您好，这支镜头没有霉斑，镜片干净通透。检查霉斑方法：第一，在强光下（如手机闪光灯）从前后两端照射镜片，观察内部有无丝状或点状物；第二，对着光源看镀膜颜色是否均匀；第三，用放大镜检查镜片边缘；第四，拍摄纯白墙面检查有无暗斑。霉斑是真菌在镜片上生长，多因潮湿环境存放导致，会影响成像质量。预防方法：存放在防潮箱或干燥柜中，湿度保持40-50%；避免从冷环境到热环境立即使用（会结露）。我手里这支镜头保存良好，无霉无尘无雾，欢迎验机。' AS answer, '镜头,霉斑,检查,防潮,镀膜' AS tags, '镜头霉斑检查与防潮保养' AS source_summary, 87 AS score
  UNION ALL SELECT 'digital_camera', '索尼24-70mm F2.8 GM镜头是几代？', '您好，这支是索尼24-70mm F2.8 GM二代（2022年发布）。和一代区别：第一，重量从886g减轻到695g，更便携；第二，最近对焦距离从0.38m缩短到0.22m（广角端）；第三，对焦速度提升，支持 shoots while zooming；第四，光学结构改进，边缘画质提升；第五，新增9片圆形光圈，散景更圆。G Master是索尼旗舰镜头系列，画质锐利，色彩还原准确，F2.8恒定光圈适合人像和活动拍摄。镜头9成新，无磕碰无划痕，无霉无尘，前后盖和遮光罩齐全。' AS answer, '索尼,24-70,F2.8,GM二代,镜头' AS tags, '索尼24-70 F2.8 GM二代说明' AS source_summary, 88 AS score
  UNION ALL SELECT 'digital_camera', 'GoPro HERO12能防水吗？需要防水壳吗？', '您好，GoPro HERO12本身防水10米（不需要防水壳），适合游泳、浮潜、冲浪等水上运动。如果您要潜水超过10米，需要购买专用防水壳（可防水60米）。HERO12主要参数：5.3K 60fps视频、2700万像素照片、HyperSmooth 6.0防抖、前后双屏。续航约70分钟（5.3K录制）。配件建议：额外电池2块、64G以上存储卡、自拍杆、 chest mount。机器9成新，使用约5次，所有功能正常，原包装和配件齐全。适合运动摄影和Vlog拍摄。' AS answer, 'GoPro,HERO12,防水,防水壳,运动相机' AS tags, 'GoPro HERO12防水性能说明' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_camera', '大疆Mini 4 Pro需要实名登记吗？能飞多远？', '您好，大疆Mini 4 Pro需要实名登记。根据民航局规定，所有250g以上的无人机都需要登记，Mini 4 Pro虽然249g以下，但仍建议登记（部分地区要求所有无人机都登记）。登记在民航局UOM系统（https://uom.caac.gov.cn）免费注册。飞行距离：图传距离最远20公里（无遮挡），实际城市环境约2-5公里。续航34分钟，支持4K 100fps视频。禁飞区：机场、军事区、政府机关等，APP会自动提示。建议购买保险，遵守当地法规。机器9成新，飞行约10次，无炸机无维修。' AS answer, '大疆,Mini4Pro,无人机,实名登记,图传' AS tags, '大疆Mini 4 Pro登记与飞行说明' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_camera', '索尼A7C II便携性怎么样？适合旅行吗？', '您好，索尼A7C II非常便携，机身仅514g，比A7M4轻了约100g，适合旅行和日常携带。A7C II是A7M4的便携版，相同3300万像素传感器、相同的Bionz XR处理器、相同的对焦系统，但机身更小巧。区别：A7C II没有电子取景器凸起（更扁平），改为侧翻屏（适合Vlog），按键较少。如果您追求便携性和画质平衡，A7C II是最佳选择。搭配40mm F2.5 G镜头，整套不到800g，旅行无负担。机器9成新，快门次数约2000次，国行正品。' AS answer, '索尼A7CII,便携,旅行,重量,微单' AS tags, '索尼A7C II便携性与旅行适用' AS source_summary, 87 AS score
  UNION ALL SELECT 'digital_camera', '拍立得相纸贵吗？一张多少钱？', '您好，拍立得相纸确实比较贵。以富士instax mini为例，一盒20张约70-90元，单张约3.5-4.5元。不同品牌价格不同：富士instax mini最便宜，instax Square方形相纸约6-8元一张，instax Wide约5-6元一张；宝丽来Originals相纸约15-20元一张。建议：相纸在电商平台买比线下便宜；买整盒比单张便宜；注意相纸保质期，过期相纸色彩会偏。拍立得适合记录生活，但成本较高，建议控制拍摄数量。机器9成新，功能正常，附赠10张相纸。' AS answer, '拍立得,相纸,instax,成本,保质期' AS tags, '拍立得相纸价格与使用成本' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_camera', '佳能5D4是单反还是微单？现在还值得买吗？', '您好，佳能5D Mark IV是单反相机，2016年发布。现在是否值得买取决于需求：优势：3040万像素全画幅，画质优秀；61点对焦系统，可靠；光学取景器无延迟；电池续航长（约900张）；镜头群丰富（EF卡口二手镜头便宜）。劣势：相比微单体积大重量重（890g）；4K视频有1.74倍裁切；无翻转屏；WiFi功能较弱。如果您是拍人像、风景、商业摄影，5D4画质完全够用，二手性价比高。如果是视频为主，建议选微单。机器9成新，快门约1.5万次。' AS answer, '佳能5D4,单反,微单,性价比,全画幅' AS tags, '佳能5D4购买价值分析' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_camera', '尼康D850像素多少？拍风景够用吗？', '您好，尼康D850是4575万像素全画幅单反，拍风景完全够用，画质非常出色。D850优势：高像素带来丰富细节，后期裁剪空间大；动态范围广，后期提亮暗部无噪点；原生ISO 64，画质纯净；机身防尘防滴，户外拍摄可靠；电池续航约1840张，旅行无续航焦虑。适合拍摄：风景、建筑、商业摄影、人像。劣势：体积大重量重（1005g）；无机身防抖；4K视频功能一般。如果您是风景摄影师，D850是顶级选择。机器9成新，快门约8000次，国行正品。' AS answer, '尼康D850,像素,风景,动态范围,全画幅' AS tags, '尼康D850风景摄影性能' AS source_summary, 88 AS score
  UNION ALL SELECT 'digital_camera', '索尼A6400是半画幅吗？和全画幅差多少？', '您好，索尼A6400是APS-C画幅（半画幅）微单，2420万像素。和全画幅区别：第一，传感器尺寸：APS-C约23.5x15.6mm，全画幅约36x24mm，全画幅面积约2.3倍；第二，虚化效果：全画幅景深更浅，背景虚化更好；第三，高感画质：全画幅高ISO下噪点更少；第四，视角：APS-C有1.5倍裁切系数，200mm镜头等效300mm；第五，价格：APS-C机身和镜头更便宜。如果您预算有限或拍运动 wildlife（裁切有优势），A6400性价比很高。机器9成新，快门约5000次。' AS answer, '索尼A6400,半画幅,APS-C,全画幅,裁切' AS tags, '索尼A6400与全画幅差异' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_camera', '镜头光圈F1.4和F1.8差很多吗？', '您好，F1.4和F1.8光圈差约1档，区别明显但不巨大。区别：第一，进光量：F1.4比F1.8进光量多约1倍，暗光环境下快门速度可以更快；第二，虚化：F1.4景深更浅，背景虚化更柔和；第三，价格：F1.4镜头通常比F1.8贵2-3倍；第四，体积重量：F1.4镜头更大更重；第五，画质：F1.4全开可能偏软，收一档到F2画质最佳，F1.8全开画质就不错。如果您是专业人像摄影师，F1.4值得投资；如果是爱好者，F1.8性价比更高。我手里这支是50mm F1.8，9成新。' AS answer, '光圈,F1.4,F1.8,虚化,进光量' AS tags, 'F1.4与F1.8光圈差异对比' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_camera', '变焦镜头和对焦镜头哪个好？', '您好，变焦镜头和定焦镜头各有优势，没有绝对好坏。变焦镜头优势：一支镜头覆盖多个焦段，方便构图，适合旅行、活动拍摄、纪实；劣势：光圈通常较小（F2.8或F4），体积较大，画质略逊。定焦镜头优势：光圈大（F1.4、F1.8），画质锐利，体积小重量轻，价格便宜；劣势：焦段固定，需要走位构图，不适合快速切换焦段。建议：旅行选变焦（24-70或24-105），人像选定焦（50或85），两者搭配使用最佳。我手里这支是24-70 F2.8变焦，9成新。' AS answer, '变焦,定焦,光圈,画质,焦段' AS tags, '变焦与定焦镜头对比选择' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_camera', 'CMOS感光元件怎么清洁？有灰尘怎么办？', '您好，CMOS有灰尘会影响成像，照片上会出现暗斑。清洁方法：第一，相机内置清洁功能（传感器震动），开机和关机时自动运行，可以手动触发；第二，气吹吹走表面灰尘，用相机专用气吹从下往上吹；第三，如果气吹吹不掉，需要用CMOS清洁棒（湿洗），沾清洁液轻轻擦拭；第四，严重污渍建议送官方售后清洁，费用约100-200元。预防：换镜头时相机朝下，避免风沙环境换镜头，不长时间空置机身。我手里这台CMOS干净无尘，欢迎到货检查。' AS answer, 'CMOS,清洁,灰尘,气吹,清洁棒' AS tags, 'CMOS感光元件清洁方法' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_camera', '相机电池续航多久？需要买备用电池吗？', '您好，相机电池续航因机型不同：单反通常500-1500张（光学取景器），微单通常300-600张（电子取景器）。以索尼A7M4为例，CIPA标称约520张，实际使用约400-500张。建议购买备用电池：第一，原装电池约300-500元，兼容电池约100-150元；第二，旅行或长时间拍摄必带备用电池；第三，低温环境电池续航会大幅缩短；第四，视频录制比拍照更耗电。我手里这台附赠1块原装电池和1块兼容电池，共2块，足够一天拍摄。电池循环次数少，健康度高。' AS answer, '电池,续航,备用电池,原装,CIPA' AS tags, '相机电池续航与备用建议' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_camera', '用什么存储卡？需要多大容量？', '您好，这台相机支持SD卡（部分支持CFexpress Type A）。存储卡选择建议：第一，容量：拍照64G够用，视频建议128G或256G；第二，速度：拍照UHS-I U3 V30（最低写入30MB/s）够用，4K视频建议UHS-II V90（写入90MB/s以上），8K或高速连拍建议CFexpress；第三，品牌：闪迪、索尼、金士顿可靠，杂牌卡可能丢数据；第四，价格：128G UHS-II约300-500元，128G UHS-I约80-150元。建议买两张卡双备，避免单卡故障丢照片。机器9成新，不含存储卡，需要另购。' AS answer, '存储卡,SD卡,容量,速度,4K视频' AS tags, '相机存储卡选择建议' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_camera', '三脚架什么材质好？碳纤维和铝合金区别？', '您好，三脚架材质主要有碳纤维和铝合金两种。碳纤维优势：重量轻（同规格轻约30%），减震性好，手感温度适中；劣势：价格贵（约铝合金2-3倍），怕横向冲击。铝合金优势：价格便宜，耐用，刚性好；劣势：重量大，低温下手感冰凉。选择建议：旅行或户外拍摄选碳纤维（便携）；影棚或预算有限选铝合金（稳定）。另外看脚架节数（3节稳定性好于4节）、最大高度、承重（需大于相机加镜头重量）。我手里这支是碳纤维三脚架，9成新，承重8kg，适合微单和单反。' AS answer, '三脚架,碳纤维,铝合金,承重,便携' AS tags, '三脚架材质选择对比' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_camera', '摄影包防水吗？能装多少器材？', '您好，这个摄影包有防泼水涂层，小雨没问题，大雨建议加防雨罩（附赠）。包的容量约15L，可以装：1台微单或单反机身、2-3支镜头（含70-200长焦）、1个闪光灯、配件若干、10寸笔记本电脑。内部隔板可调节，灵活分区。背负系统舒适，肩带和腰带加厚，长时间背负不累。侧面有三脚架挂点。包体有防盗设计，拉链朝向身体。适合旅行摄影和日常外拍。9成新，无破损无污渍，拉链顺滑。如果您器材较多，建议选更大容量。' AS answer, '摄影包,防水,容量,隔板,背负' AS tags, '摄影包防水与容量说明' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_camera', '闪光灯是原厂还是副厂？功率多少？', '您好，这支闪光灯是神牛V860III（副厂），GN60功率，覆盖20-200mm焦段。和原厂区别：第一，价格：神牛约500元，原厂约2000-3000元；第二，功能：神牛支持TTL自动、HSS高速同步、无线引闪，功能齐全；第三，兼容性：神牛对索尼、佳能、尼康都有对应版本，兼容性良好；第四，做工：原厂做工更好，神牛塑料感重一些。我个人用神牛V860III两年，稳定可靠，性价比很高。支持锂电池（续航约650次全光），回电快。闪光灯9成新，功能正常。' AS answer, '闪光灯,神牛,GN60,TTL,副厂' AS tags, '闪光灯原厂副厂对比' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_camera', 'UV镜和CPL滤镜有什么用？需要买吗？', '您好，UV镜和CPL滤镜作用不同。UV镜：主要保护镜头前组镜片，防止划伤和灰尘，对画质影响很小（优质UV镜）；价格50-300元；建议常装。CPL偏振镜：消除非金属表面反光（玻璃、水面），让天空更蓝，色彩更饱和；价格100-500元；适合风景摄影。其他滤镜：ND减光镜（长曝光用）、GND渐变镜（光比大场景）。建议：UV镜买好的（B+W、海大、NiSi），CPL根据需求购买。我手里这个是海大UV镜，9成新，镀膜完好。' AS answer, 'UV镜,CPL,滤镜,偏振,保护' AS tags, 'UV镜与CPL滤镜作用说明' AS source_summary, 81 AS score
  UNION ALL SELECT 'digital_camera', '相机有保修吗？保修期到什么时候？', '您好，这台相机是国行正品，有官方保修。保修期从购买日起算1年（机身），镜头1年。保修方式：到品牌官方售后服务中心（索尼、佳能、尼康全国都有），凭保修卡和发票即可保修。保修范围：非人为损坏的故障（如传感器故障、主板问题、快门故障）。不保修范围：进水、摔坏、自行拆修、人为损坏。我保留了原厂包装盒、保修卡、发票，过户后保修不影响。机器9成新，目前无任何故障，所有功能正常。建议到货后到官方售后查询保修状态。' AS answer, '保修,国行,官方售后,保修卡,发票' AS tags, '相机保修期与售后说明' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_camera', '怎么辨别相机真假？担心买到翻新机', '您好，辨别相机真假方法：第一，序列号：机身底部和包装盒上的序列号必须一致，到品牌官网查询保修状态，正品有记录；第二，EXIF信息：拍摄照片后用软件查看EXIF，可以看到机身序列号、快门次数等信息；第三，外观工艺：正品做工精细，接缝均匀，螺丝无拧痕；第四，功能测试：所有按键、拨轮、屏幕、对焦、防抖等功能正常；第五，官方售后检测：最权威的方式。翻新机判断：螺丝有拧痕、机身有更换部件痕迹、快门次数异常低但外观旧。我手里这台是国行正品，欢迎任何方式验机。' AS answer, '真假,翻新机,序列号,EXIF,验机' AS tags, '相机真假辨别方法' AS source_summary, 87 AS score
  UNION ALL SELECT 'digital_camera', '水货相机和国行有什么区别？', '您好，水货和国行相机主要区别：第一，保修：国行全国联保1年，水货无官方保修，只能找卖家或第三方维修；第二，菜单语言：国行支持中文，水货可能需要刷机（部分品牌）；第三，价格：水货通常便宜500-2000元；第四，电源适配器：国行是国标插头，水货可能需要转接头；第五，售后服务：国行可以到官方售后免费检测和维修，水货不行。我个人建议：中低价位相机买国行（差价小，保修方便）；高端相机可以考虑水货（差价大，但需找可靠卖家）。我手里这台是国行正品，发票齐全。' AS answer, '水货,国行,保修,菜单,价格' AS tags, '水货与国行相机差异' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_camera', '相机成色怎么定义？9成新和95新区别？', '您好，相机成色定义：全新未拆封等于全新；99新等于仅拆封未使用或使用1-2次无任何痕迹；95新等于使用少，无划痕无磕碰，功能完好，快门次数少；9新等于正常使用，有轻微划痕或磨损，功能正常；8新等于有明显使用痕迹，可能有磕碰。我手里这台是9成新，使用约半年，快门约5000次，有轻微使用痕迹（手柄处轻微磨亮），无磕碰无划痕，所有功能正常。建议购买二手相机选择9成新以上，性价比和成色平衡较好。购买前确认快门次数、有无拆修、有无进水。' AS answer, '成色,9成新,95新,快门次数,定义' AS tags, '相机成色等级定义' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_camera', '配件都齐全吗？送什么？', '您好，配件齐全：原厂包装盒、机身盖、热靴盖、肩带、电池（1块原装）、充电器、电源线、说明书、保修卡。我额外赠送：32G SD卡一张、相机包一个、气吹一个、清洁布一张。所有配件都是原厂正品，没有第三方替换（除赠送品外）。包装盒序列号与机身一致，可以核对。如果您不需要配件只要裸机，我可以优惠200元。机器9成新，配件几乎全新。建议保留原厂包装盒，以后转手或保修时可能用到。' AS answer, '配件,原装,SD卡,相机包,赠品' AS tags, '相机配件清单与赠品' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_camera', '支持验机吗？相机怎么验？', '您好，支持验机。验机方式：第一，闲鱼验机服务（部分城市支持），下单时选择；第二，到品牌官方售后检测，免费或少量费用；第三，到当地相机店请专业人士检测；第四，自行检测：检查外观、快门次数（用软件查看EXIF）、CMOS有无灰尘（拍纯白墙）、对焦是否准确、防抖是否正常、所有按键和拨轮、视频录制、WiFi连接等。验机内容：配置是否与描述一致、快门次数、有无拆修、有无进水、功能是否正常。机器9成新，欢迎任何方式验机，有问题全额退款。' AS answer, '验机,快门次数,CMOS,对焦,防抖' AS tags, '相机验机方法与内容' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_camera', '能拍视频吗？4K画质怎么样？', '您好，这台相机支持4K视频拍摄。以索尼A7M4为例：4K 60p（Super35裁切）或4K 30p（全画幅无裁切），10位4:2:2色彩深度，S-Log3和S-Cinetone色彩模式，画质非常出色。适合拍摄：短片、Vlog、商业视频、婚礼视频。建议：4K视频文件大，需要高速SD卡（UHS-II V90）；长时间录制需要散热（A7M4有过热保护）；收音建议用外接麦克风；稳定画面建议用稳定器或机身防抖。机器9成新，视频功能正常，无过热问题。如果您是视频创作者，这台相机完全够用。' AS answer, '4K视频,画质,S-Log3,录制,防抖' AS tags, '相机4K视频拍摄能力' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_camera', '相机WiFi怎么连接手机？能远程控制吗？', '您好，这台相机支持WiFi和蓝牙连接手机，可以远程控制和传输照片。连接方法：第一，下载品牌官方APP（索尼Imaging Edge、佳能Camera Connect、尼康SnapBridge）；第二，相机菜单中开启WiFi/蓝牙功能；第三，手机APP搜索相机，按提示配对连接（首次需要输入密码或扫码）。功能：远程控制拍摄（手机实时取景、调整参数、遥控快门，适合自拍和延时摄影）；照片传输到手机（选择照片发送到手机，方便分享社交媒体）；自动同步（部分相机支持拍摄后自动传到手机）；GPS记录（手机GPS数据同步到照片）。机器9成新，WiFi连接正常，欢迎测试。' AS answer, 'WiFi,手机连接,远程控制,传输,APP' AS tags, '相机WiFi连接手机与远程控制' AS source_summary, 82 AS score
) q
JOIN ai_cs_kb_category c ON c.code = q.code AND c.deleted = 0 AND c.parent_id IS NOT NULL;


-- ----------------------------------------------------------------------------
-- 4. digital_audio（音频设备）- 30 条
-- ----------------------------------------------------------------------------
INSERT IGNORE INTO ai_cs_learned_kb (
    category_id, question, answer, tags, source_summary,
    content_hash, score, review_status, enabled, vector_indexed,
    source_count, source_conv_ids, learn_batch_id, sensitive_filtered,
    source_type, deleted, created_time, updated_time
)
SELECT c.id, q.question, q.answer, q.tags, q.source_summary,
       MD5(CONCAT(q.question, q.answer)), q.score, 'approved', 1, 1,
       1, NULL, 'seed-v1.52', 1, 'seed', 0, NOW(), NOW()
FROM (
  SELECT 'digital_audio' AS code, '怎么辨别AirPods Pro真假？担心买到高仿' AS question, '您好，辨别AirPods Pro真假有以下几个方法：第一，序列号：包装盒、充电盒盖内、手机设置-蓝牙-AirPods中三处序列号必须一致，到苹果官网查询保修状态；第二，连接动画：正品开盖靠近iPhone会弹出连接动画，高仿可能没有或动画粗糙；第三，降噪效果：正品降噪效果明显，高仿几乎没有降噪；第四，空间音频：正品支持空间音频和头部追踪，高仿没有；第五，固件版本：在设置-蓝牙-AirPods中可以看到固件版本，高仿可能显示异常。我手里这副是国行正品，包装盒、发票齐全，支持任何方式验机。' AS answer, 'AirPodsPro,真假,序列号,降噪,高仿' AS tags, 'AirPods Pro真假辨别方法' AS source_summary, 90 AS score
  UNION ALL SELECT 'digital_audio', '索尼WH-1000XM5降噪效果怎么样？比XM4好吗？', '您好，索尼WH-1000XM5降噪效果非常出色，比XM4提升明显。XM5改进：第一，8个麦克风（XM4是6个）收音更精准；第二，V1集成处理器降噪算法升级，低频降噪更好；第三，新一代降噪隔离驱动单元；第四，重量从254g减轻到250g，更舒适；第五，通话质量提升（波束成形麦克风）。实测在地铁、飞机等环境降噪效果优秀，几乎听不到外界噪音。续航30小时，支持快充（3分钟用3小时）。我手里这副9成新，国行正品，无磕碰无划痕，耳罩无脱皮。' AS answer, '索尼,XM5,降噪,XM4,对比' AS tags, '索尼WH-1000XM5降噪性能与XM4对比' AS source_summary, 89 AS score
  UNION ALL SELECT 'digital_audio', '漫步者音箱音质怎么样？性价比高吗？', '您好，漫步者音箱性价比很高，同价位音质表现优秀。以漫步者R1700BT为例：2.0声道，60W功率，5寸低音加19mm丝膜高音，音质均衡，低频充足，中频人声清晰，高频细腻。蓝牙5.0连接稳定，支持光纤、同轴、RCA多种输入。适合桌面近场聆听、看视频、听音乐。漫步者是国内老牌音响厂商，质量可靠，售后有保障。相比国外品牌同价位音箱，漫步者配置更高、音质更好。如果您预算300-800元，漫步者是首选。机器9成新，无磕碰无划痕，所有接口正常。' AS answer, '漫步者,音箱,音质,性价比,蓝牙' AS tags, '漫步者音箱音质与性价比' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_audio', 'JBL蓝牙音箱防水吗？能带去浴室吗？', '您好，JBL Flip 6支持IP67防水防尘，可以带去浴室、泳池、海边使用。IP67含义：完全防尘，可在1米深水中浸泡30分钟。使用注意：第一，防水不防水蒸气，浴室建议放在远离淋浴的位置；第二，使用后用干布擦干，避免长期潮湿；第三，充电口防水盖要盖好，充电时不防水；第四，海水使用后要用清水冲洗，避免盐分腐蚀。Flip 6音质：30W功率，低频强劲，适合户外和派对。续航12小时，蓝牙5.1连接稳定。机器9成新，无磕碰，防水性能正常。' AS answer, 'JBL,防水,IP67,蓝牙音箱,浴室' AS tags, 'JBL蓝牙音箱防水性能' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_audio', '铁三角耳机适合听什么音乐？', '您好，铁三角耳机以中高频出色著称，适合听人声、古典、轻音乐。以铁三角ATH-M50x为例：监听级耳机，频率响应15-28000Hz，阻抗38欧姆，灵敏度高，易于驱动。音质特点：中高频清晰细腻，人声还原准确，高频延伸好但不刺耳；低频量感适中，下潜一般，不适合重低音爱好者。适合：人声、爵士、古典、轻音乐、监听混音。不适合：摇滚、电子、嘻哈等重低音音乐。如果您喜欢人声或古典，铁三角是不错的选择。机器9成新，耳罩无脱皮，线材完好。' AS answer, '铁三角,耳机,人声,中高频,监听' AS tags, '铁三角耳机音质特点与适用' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_audio', '森海塞尔耳机和索尼哪个好？', '您好，森海塞尔和索尼各有优势，取决于使用场景。森海塞尔优势：音质纯正，中高频出色，适合听古典、人声；做工扎实，耐用；有线耳机音质天花板（HD600、HD800）。劣势：降噪一般，无线型号较少。索尼优势：降噪行业领先（WH-1000XM5）；无线耳机体验好；功能丰富（LDAC、空间音频）。劣势：音质偏数码味，中高频不如森海。选择建议：注重音质选森海（尤其有线），注重降噪和便携选索尼。我手里这副是森海塞尔HD600，开放式耳机，音质出色，9成新。' AS answer, '森海塞尔,索尼,音质,降噪,对比' AS tags, '森海塞尔与索尼耳机对比' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_audio', '马歇尔音箱音质怎么样？适合听什么？', '您好，马歇尔音箱音质有特色，适合摇滚和流行乐。以Marshall Stanmore III为例：2.1声道，80W功率，5.25寸低音加两个0.75寸高音，音质特点：低频强劲有力，中频厚实温暖，高频略暗但耐听。标志性的吉他音箱外观，复古颜值高。适合听：摇滚、流行、电子、嘻哈等节奏感强的音乐。不太适合：古典、爵士等需要细腻中高频的音乐。蓝牙5.2加3.5mm有线输入，连接灵活。机器9成新，外观无磕碰，旋钮和按键正常，皮革面板完好。如果您喜欢摇滚和复古风格，马歇尔很适合。' AS answer, '马歇尔,音箱,摇滚,低频,复古' AS tags, '马歇尔音箱音质特点' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_audio', 'AKG K371是监听耳机吗？适合混音吗？', '您好，AKG K371是专业监听耳机，适合混音和录音。参数：50mm驱动单元，频率响应5-40000Hz，阻抗32欧姆，灵敏度114dB，易于驱动。音质特点：频响平直，没有刻意美化，适合监听；中性平衡，三频均衡；解析力高，细节丰富；声场适中，定位准确。适合：录音监听、混音、视频剪辑、专业听音。不太适合：日常休闲听歌（音质太素，没有讨喜的调音）。K371是封闭式耳机，隔音好，不漏音。机器9成新，耳罩无脱皮，头梁无裂痕。如果您做音乐或视频，K371性价比很高。' AS answer, 'AKG,K371,监听,混音,频响' AS tags, 'AKG K371监听耳机说明' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_audio', '飞利浦耳机怎么样？有线还是无线好？', '您好，飞利浦耳机性价比不错，有线无线各有优势。有线耳机优势：音质更好（无损传输），无需充电，价格便宜，延迟低（适合游戏）；劣势：线材缠绕，活动受限。无线耳机优势：便携，运动方便，没有线材束缚；劣势：需要充电，音质略逊（蓝牙编码压缩），有延迟，价格贵。选择建议：家用听音乐选有线（飞利浦SHP9500是性价比之王）；运动或通勤选无线（飞利浦TAT8506真无线）。飞利浦是老牌音频厂商，质量可靠。我手里这副是有线SHP9500，开放式耳机，音质出色，9成新。' AS answer, '飞利浦,耳机,有线,无线,SHP9500' AS tags, '飞利浦耳机有线无线对比' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_audio', '小米耳机和Bose比怎么样？', '您好，小米耳机和Bose定位不同，差距明显。小米耳机优势：价格便宜（200-500元），功能丰富，性价比高；适合日常通勤、运动。劣势：降噪和音质不如Bose，做工一般。Bose优势：降噪行业顶级（QuietComfort系列）；音质温暖舒适，长时间聆听不累；佩戴舒适；做工精致。劣势：价格贵（1500-2500元）。选择建议：预算有限选小米（Redmi Buds 5 Pro降噪不错）；预算充足注重降噪和舒适选Bose。我手里这副是Bose QC45，降噪出色，佩戴舒适，9成新。如果您是商务出差频繁，Bose值得投资。' AS answer, '小米,Bose,降噪,音质,对比' AS tags, '小米与Bose耳机对比' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_audio', '华为FreeBuds Pro 3降噪怎么样？', '您好，华为FreeBuds Pro 3降噪效果出色，属于真无线耳机第一梯队。降噪性能：双麦克风混合降噪，最大降噪深度50dB，在地铁、公交等环境降噪效果明显。音质：11mm四磁铁动圈单元，支持LDAC和L2HC 3.0高清音频编码，音质细腻。其他功能：空间音频、头部追踪；骨声纹通话降噪；智慧降噪（根据环境自动切换）。续航：单次约7小时，加充电盒约30小时。佩戴舒适，长时间使用不胀痛。机器9成新，国行正品，无磕碰无划痕。如果您是华为手机用户，FreeBuds Pro 3体验最佳。' AS answer, '华为,FreeBudsPro3,降噪,LDAC,真无线' AS tags, '华为FreeBuds Pro 3降噪性能' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_audio', 'BOSE SoundLink Flex音质怎么样？', '您好，BOSE SoundLink Flex音质出色，是便携蓝牙音箱的优秀选择。参数：单声道，20W功率，IP67防水防尘，续航12小时。音质特点：BOSE标志性音质，中低频厚实温暖，人声表现优秀；PositionIQ技术自动检测方向优化音质；被动辐射器增强低频。适合：户外露营、桌面听音、看视频。体积小巧（190x80x80mm），重量600g，便携性好。防水防摔，户外使用放心。机器9成新，无磕碰无划痕，防水性能正常。如果您注重便携和音质平衡，SoundLink Flex很适合。相比JBL Flip 6，BOSE中低频更好，JBL低频更猛。' AS answer, 'BOSE,SoundLinkFlex,音质,防水,便携' AS tags, 'BOSE SoundLink Flex音质说明' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_audio', '麦克风是电容还是动圈？适合录什么？', '您好，这支是电容麦克风（以铁三角AT2020为例），适合录音棚和家庭录音。电容麦克风和动圈麦克风区别：电容麦：灵敏度高，频响宽，细节丰富，适合人声、乐器、播客录音；需要幻象电源（48V）；对环境噪音敏感，需要安静房间。动圈麦：灵敏度低，频响窄，耐震耐用，适合现场演出、KTV、直播；不需要幻象电源；对环境噪音不敏感。选择建议：录音棚或安静房间选电容麦（AT2020性价比高）；嘈杂环境或现场演出选动圈麦（舒尔SM58经典）。我手里这支是AT2020电容麦，9成新，配防震架和防喷罩。' AS answer, '麦克风,电容,动圈,录音,幻象电源' AS tags, '电容与动圈麦克风对比' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_audio', '声卡有什么用？直播需要吗？', '您好，声卡的作用是提升音频质量和提供接口。直播或录音建议用声卡。声卡功能：第一，提升音质：专业AD/DA转换，比电脑集成声卡音质好；第二，提供接口：XLR麦克风接口（需幻象电源）、乐器接口、监听耳机接口；第三，增益控制：调节麦克风灵敏度；第四，效果器：部分声卡支持混响、压缩等效果；第五，零延迟监听：实时听到自己的声音。推荐：入门选Focusrite Scarlett Solo（约800元）；直播选艾肯iCON Mobile U（约1200元）；专业选Apogee或RME。机器9成新，所有接口正常。' AS answer, '声卡,直播,录音,XLR,幻象电源' AS tags, '声卡作用与直播选择' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_audio', '功放和音响怎么搭配？功率要匹配吗？', '您好，功放和音响搭配需要考虑功率、阻抗、灵敏度等。功率匹配：功放功率建议是音响额定功率的1.2-2倍，避免小马拉大车（功放失真烧高音）或大马拉小车（浪费）。阻抗匹配：功放阻抗要小于或等于音响阻抗（功放8欧接音响8欧或4欧都可以，反过来不行）。灵敏度：音响灵敏度低（85dB以下）需要更大功率功放。听音风格：暖声功放配亮声音响，避免声音过亮或过暗。建议：同品牌搭配通常调音更搭；入门选天龙、雅马哈功放配JBL或尊宝音响。我手里这台是天龙功放，8成新，所有通道正常。' AS answer, '功放,音响,功率,阻抗,搭配' AS tags, '功放与音响搭配原则' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_audio', '降噪耳机和隔音耳机哪个好？', '您好，降噪耳机和隔音耳机原理不同，各有优势。降噪耳机（主动降噪）：通过麦克风采集外界噪音，生成反相声波抵消噪音；对低频噪音（引擎、空调）效果极佳；对中高频人声效果一般；需要供电。隔音耳机（被动隔音）：通过物理材质隔绝噪音；对中高频（人声、键盘声）效果较好；对低频效果一般；不需要供电。选择建议：通勤出差（地铁、飞机）选降噪耳机（索尼XM5、Bose QC45）；学习办公（人声、键盘声）选隔音耳机或入耳式；极端环境可以两者结合（降噪耳机加隔音耳罩）。机器9成新。' AS answer, '降噪,隔音,主动降噪,被动降噪,耳机' AS tags, '降噪与隔音耳机对比' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_audio', '蓝牙耳机续航多久？充电盒能充几次？', '您好，蓝牙真无线耳机续航因型号不同：单次续航通常4-8小时，加充电盒总续航20-40小时。以AirPods Pro为例：单次约5小时（降噪开启约4.5小时），充电盒约24小时总续航，充电盒可以给耳机充约4-5次。充电方式：充电盒有线充电（Lightning或Type-C）；部分支持无线充电（Qi标准）；快充：充电5分钟使用1小时。电池寿命：锂电池约500次充放电循环后容量降至80%，日常使用约2-3年。建议：不用时放回充电盒；避免完全放电；高温环境避免使用。机器9成新，电池健康度约95%。' AS answer, '蓝牙耳机,续航,充电盒,快充,电池' AS tags, '蓝牙耳机续航与充电说明' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_audio', '蓝牙连接稳定吗？会断连吗？', '您好，这台蓝牙音箱连接稳定，很少断连。蓝牙连接稳定性影响因素：第一，蓝牙版本：蓝牙5.0以上连接更稳定、距离更远（约10米无遮挡）；第二，干扰：WiFi、微波炉等2.4GHz设备会干扰蓝牙，建议远离；第三，障碍物：墙壁、金属会减弱信号，建议无遮挡使用；第四，设备兼容性：部分老设备蓝牙兼容性差；第五，电量低：电量低于20%可能不稳定。断连解决方法：重新配对；清除设备的蓝牙记录；重启设备；更新固件。机器9成新，蓝牙5.2连接稳定，实测10米内无断连。' AS answer, '蓝牙,连接,断连,稳定,蓝牙5.0' AS tags, '蓝牙连接稳定性说明' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_audio', '有线耳机和无线耳机音质差多少？', '您好，有线耳机音质通常优于无线耳机，但差距在缩小。有线耳机优势：无损传输，没有蓝牙编码压缩；无需供电，没有电池续航问题；延迟低，适合游戏和视频；同价位音质更好。无线耳机优势：便携，无束缚；运动方便；功能丰富（降噪、空间音频）。音质差距：蓝牙编码（LDAC、aptX HD）已接近有线音质，但仍有差距；高端有线耳机（1000元以上）音质明显优于同价位无线。选择建议：追求音质选有线；追求便携和功能选无线。我手里这副是有线耳机，音质出色，9成新。' AS answer, '有线,无线,音质,蓝牙编码,LDAC' AS tags, '有线与无线耳机音质对比' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_audio', '耳机兼容性怎么样？苹果安卓都能用吗？', '您好，这台耳机兼容性很好，苹果安卓都能用。兼容性说明：第一，有线耳机：3.5mm接口耳机兼容所有有耳机口的设备；Type-C或Lightning接口耳机只兼容对应接口设备。第二，蓝牙耳机：基本兼容所有蓝牙设备，但部分功能可能有差异（如AirPods在安卓上无法使用空间音频、弹窗动画等专属功能）。第三，功能差异：苹果生态（AirPods加iPhone）体验最佳，自动切换、查找耳机等；安卓生态（索尼加华为等）也有各自特色功能。选择建议：苹果用户选AirPods；安卓用户选索尼或华为。机器9成新，蓝牙连接兼容性好。' AS answer, '兼容性,苹果,安卓,蓝牙,有线' AS tags, '耳机兼容性与设备适配' AS source_summary, 81 AS score
  UNION ALL SELECT 'digital_audio', '配件都齐全吗？送什么？', '您好，配件齐全：原厂包装盒、充电盒、耳机、硅胶耳塞（多尺寸）、Type-C充电线、说明书、保修卡。我额外赠送：保护套一个、收纳袋一个、清洁布一张。所有配件都是原厂正品，没有第三方替换（除赠送品外）。包装盒序列号与耳机一致，可以核对。如果您不需要配件只要裸机，我可以优惠50元。机器9成新，配件几乎全新。建议保留原厂包装盒，以后转手或保修时可能用到。耳机功能全部正常，欢迎到货验机。' AS answer, '配件,原装,充电盒,耳塞,赠品' AS tags, '耳机配件清单与赠品' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_audio', '有保修吗？保修期到什么时候？', '您好，这台耳机是国行正品，有官方保修。保修期从购买日起算1年。保修方式：到品牌官方售后服务中心（苹果、索尼、华为等全国都有），凭保修卡和发票即可保修。保修范围：非人为损坏的故障（如电池故障、单侧无声、连接故障）。不保修范围：进水（非防水型号）、摔坏、自行拆修、人为损坏、耳罩磨损（属于耗材）。我保留了原厂包装盒、保修卡、发票，过户后保修不影响。机器9成新，目前无任何故障。建议到货后到官方查询保修状态。' AS answer, '保修,国行,官方售后,保修卡,发票' AS tags, '耳机保修期与售后说明' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_audio', '怎么辨别真假耳机？担心买到高仿', '您好，辨别耳机真假方法：第一，序列号：包装盒、机身、APP中三处序列号必须一致，到品牌官网查询；第二，连接弹窗：正品有品牌专属连接动画（AirPods、华为FreeBuds等），高仿可能没有或粗糙；第三，音质：正品音质清晰均衡，高仿音质模糊或低频过重；第四，降噪：正品降噪效果明显，高仿几乎没有降噪；第五，做工：正品接缝均匀、材质质感好，高仿做工粗糙；第六，功能：正品支持空间音频、固件更新等，高仿可能不支持。我手里这副是国行正品，欢迎任何方式验机。' AS answer, '真假,高仿,序列号,降噪,验机' AS tags, '耳机真假辨别方法' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_audio', '国行和水货耳机有什么区别？', '您好，国行和水货耳机主要区别：第一，保修：国行全国联保1年，水货无官方保修；第二，连接功能：部分品牌专属功能（如AirPods弹窗、空间音频）在国行设备上体验最佳；第三，充电接口：国行可能是国标插头，水货可能需要转接头；第四，价格：水货通常便宜100-500元；第五，固件：部分水货可能无法更新到最新固件。选择建议：低价位耳机买国行（差价小，保修方便）；高价位耳机可以考虑水货（差价大，但需找可靠卖家）。我手里这副是国行正品，发票齐全，保修期内。' AS answer, '国行,水货,保修,连接,价格' AS tags, '国行与水货耳机差异' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_audio', '耳机成色怎么样？有磨损吗？', '您好，这副耳机9成新，使用约半年，有轻微使用痕迹但无磕碰无划痕。具体成色：充电盒外观有轻微磨亮（正常使用痕迹），无磕碰无凹陷；耳机本体无划痕无污渍；耳塞完好无破损；充电触点干净无氧化；开盖阻尼正常，盖子不松。功能全部正常：蓝牙连接稳定、降噪效果良好、触控灵敏、续航正常。如果您对成色要求极高，我手里还有一副95新的同款，价格贵100元。建议购买二手耳机选择9成新以上，性价比和成色平衡较好。机器9成新，欢迎到货验机。' AS answer, '成色,9成新,磨损,充电盒,耳塞' AS tags, '耳机成色与磨损说明' AS source_summary, 81 AS score
  UNION ALL SELECT 'digital_audio', '价格还能便宜吗？送什么？', '您好，这个价格已经是底价了，相比同款二手市场便宜100元左右。如果您诚心要，我可以再优惠50元，并赠送以下配件：第一，硅胶耳塞一套（多尺寸）；第二，收纳袋一个；第三，清洁布一张；第四，Type-C充电线一根。这样下来比市场便宜200元了。您也知道闲鱼数码利润薄，主要走量。如果走验机服务，验机费20元我承担。已经是底价了，再低就亏本了，希望您理解。耳机9成新，功能正常，性价比很高。' AS answer, '价格,优惠,赠品,耳塞,验机' AS tags, '耳机价格谈判与赠品' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_audio', '支持验机吗？耳机怎么验？', '您好，支持验机。验机方式：第一，闲鱼验机服务（部分城市支持）；第二，到品牌官方售后检测；第三，自行检测：检查外观、序列号核对、连接测试、降噪测试、音质测试、续航测试、触控测试、固件版本查询等。验机内容：配置是否与描述一致、有无拆修、有无进水、功能是否正常、电池健康度。耳机验机重点：左右耳音量是否一致、降噪效果是否正常、连接是否稳定、充电盒是否正常充电。机器9成新，欢迎任何方式验机，有问题全额退款。' AS answer, '验机,序列号,降噪,音质,电池' AS tags, '耳机验机方法与内容' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_audio', '耳机佩戴舒适吗？长时间戴会痛吗？', '您好，这副耳机佩戴舒适，长时间使用不痛。佩戴舒适度因素：第一，重量：轻量化设计减少耳部负担；第二，耳塞材质：硅胶耳塞柔软亲肤，多尺寸可选；第三，入耳角度：符合人体工学设计，贴合耳道；第四，透气性：部分型号有通气孔减压。佩戴建议：选择合适尺寸的耳塞（太大胀痛，太小漏音和掉落）；每1-2小时取下休息；运动时选择有耳翼或耳挂的型号；对入耳式不适的用户可以考虑半入耳或头戴式。机器9成新，耳塞完好，佩戴舒适。' AS answer, '佩戴,舒适,耳塞,入耳,重量' AS tags, '耳机佩戴舒适度说明' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_audio', '发货用什么快递？包装安全吗？', '您好，耳机属于小型数码，默认发顺丰快递，包邮（偏远地区除外）。包装方式：原厂包装盒加气泡膜加顺丰专用小箱，确保运输无损。发货前会拍摄视频留证，包括耳机外观、序列号、配件、包装过程。签收时建议您当面验货，确认外观无损、功能正常后再签收。如有问题可以拒收并联系我。发货时间一般是付款后24小时内，节假日顺延。如果不接受顺丰，可以发中通圆通，邮费同样我承担。机器9成新，欢迎到货验机。' AS answer, '顺丰,包邮,包装,发货,验货' AS tags, '耳机快递发货说明' AS source_summary, 79 AS score
  UNION ALL SELECT 'digital_audio', '蓝牙耳机延迟怎么样？能玩游戏吗？', '您好，蓝牙耳机有延迟，玩游戏有影响但可以接受。延迟原因：蓝牙编码压缩和解码需要时间，不同编码延迟不同：SBC约200-250ms（通用编码，延迟较高）；AAC约150-200ms（苹果设备）；aptX约150ms（安卓部分设备）；aptX Low Latency约40ms（游戏专用）；LDAC约200ms（音质优先）。游戏影响：音游、射击游戏对延迟敏感，可能影响体验；角色扮演、策略游戏影响较小。建议：玩游戏选支持aptX LL的耳机和手机；苹果生态用AirPods（延迟约140ms，苹果优化较好）；有线耳机延迟最低（约10ms），竞技游戏首选。机器9成新，蓝牙延迟正常，日常使用和视频无感知延迟。' AS answer, '蓝牙,延迟,游戏,编码,LDAC' AS tags, '蓝牙耳机延迟与游戏适用性' AS source_summary, 81 AS score
) q
JOIN ai_cs_kb_category c ON c.code = q.code AND c.deleted = 0 AND c.parent_id IS NOT NULL;


-- ----------------------------------------------------------------------------
-- 5. digital_appliance_home（家用电器）- 30 条
-- ----------------------------------------------------------------------------
INSERT IGNORE INTO ai_cs_learned_kb (
    category_id, question, answer, tags, source_summary,
    content_hash, score, review_status, enabled, vector_indexed,
    source_count, source_conv_ids, learn_batch_id, sensitive_filtered,
    source_type, deleted, created_time, updated_time
)
SELECT c.id, q.question, q.answer, q.tags, q.source_summary,
       MD5(CONCAT(q.question, q.answer)), q.score, 'approved', 1, 1,
       1, NULL, 'seed-v1.52', 1, 'seed', 0, NOW(), NOW()
FROM (
  SELECT 'digital_appliance_home' AS code, '海尔冰箱能效等级是多少？耗电吗？' AS question, '您好，这台海尔冰箱是一级能效，综合耗电量约0.58度/天，非常省电。一级能效是最高等级，相比三级能效每年省电约100度。冰箱耗电量因素：第一，容量大小（越大越耗电）；第二，能效等级（一级最省电）；第三，使用习惯（频繁开关门增加耗电）；第四，环境温度（夏天耗电多）；第五，存放量（太满或太空都耗电）。建议：冰箱放置在通风阴凉处，远离热源；门密封条保持完好；除霜及时；温度设置合理（冷藏5度，冷冻-18度）。机器9成新，能效标签完好，制冷正常。' AS answer, '海尔冰箱,能效等级,耗电,一级能效,省电' AS tags, '海尔冰箱能效等级与耗电量' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_appliance_home', '美的洗衣机是滚筒还是波轮？容量多大？', '您好，这台美的洗衣机是滚筒式，容量10kg，适合3-5口之家。滚筒和波轮区别：滚筒：对衣物磨损小，省水（约50L/次），可加热洗，功能多（羊毛、羽绒、蒸汽），但洗涤时间长（1-2小时），价格贵；波轮：洗涤时间短（30-40分钟），价格便宜，但衣物磨损大，易缠绕，费水（约100L/次）。选择建议：经常洗高档衣物选滚筒；只洗日常衣物选波轮。10kg容量可以洗：约20件衬衫，或5条牛仔裤，或1床双人被。机器9成新，所有功能正常，内筒干净无异味。' AS answer, '美的,洗衣机,滚筒,波轮,容量' AS tags, '美的洗衣机类型与容量' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_appliance_home', '格力空调是几匹的？适用多大面积？', '您好，这台格力空调是1.5匹，适用面积15-22平方米。空调匹数和适用面积：1匹：制冷面积约12-17平米；1.5匹：约15-22平米；2匹：约20-29平米；3匹：约30-40平米。选择建议：卧室选1-1.5匹；客厅选2-3匹（根据面积）；顶楼或西晒建议加大一档。能效等级：一级最省电，三级最费电，建议选一级能效。变频vs定频：变频省电、温控精准、噪音小，建议选变频。机器9成新，制冷制热正常，噪音小，无漏水。附遥控器和说明书，国行正品。' AS answer, '格力空调,匹数,面积,变频,能效' AS tags, '格力空调匹数与适用面积' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_appliance_home', '小米电视是4K的吗？画质怎么样？', '您好，这台小米电视是4K分辨率（3840x2160），画质不错。小米电视EA55 2022款参数：55寸，4K HDR，全面屏，金属机身，支持杜比音效。画质特点：4K分辨率画面细腻，HDR提升对比度和色彩；色彩还原准确；运动补偿减少拖影；适合看视频、电影、玩游戏。功能：内置小爱同学语音助手；PatchWall系统资源丰富；支持手机投屏；可控制智能家居。接口：HDMI 2.0x2、USB 2.0x2、网线口、AV口。机器9成新，屏幕无坏点无漏光，国行正品。' AS answer, '小米电视,4K,画质,HDR,智能' AS tags, '小米电视4K画质与功能' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_appliance_home', '松下微波炉功率多大？能烧烤吗？', '您好，这台松下微波炉是23L容量，1000W功率，支持变频和烧烤功能。功能：微波加热（1000W，6档火力）；变频技术（受热均匀，不外熟内冷）；烧烤功能（石英管加热，可烤面包、鸡翅）；自动菜单（一键烹饪常见食物）；解冻功能（按重量自动解冻）。23L容量适合3-4口之家，可以放标准盘子。使用建议：微波加热用微波专用容器，不用金属容器；烧烤用烤架和烤盘；加热食物加盖防止溅出。机器9成新，功能全部正常，内胆干净无锈蚀，转盘完好。' AS answer, '松下,微波炉,功率,烧烤,变频' AS tags, '松下微波炉功率与功能' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_appliance_home', '象印电饭煲是国产还是进口？煮饭好吃吗？', '您好，这台象印电饭煲是日本进口，煮饭非常好吃。象印是日本三大电饭煲品牌之一（象印、虎牌、东芝），以IH电磁加热和厚釜内胆著称。这台是IH压力电饭煲，特点：IH电磁加热（立体受热，米饭粒粒分明）；压力烹饪（提升米饭甜度和口感）；厚釜内胆（蓄热好，受热均匀）；多种烹饪模式（白米、寿司、糙米、粥、煲汤）；预约功能（24小时预约）。煮饭对比：IH电饭煲煮出的米饭比普通电饭煲更香更糯，粒粒分明。机器9成新，内胆无划痕，国行正品（部分水货）。' AS answer, '象印,电饭煲,IH,进口,煮饭' AS tags, '象印电饭煲进口与煮饭效果' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_appliance_home', '戴森吸尘器是哪款？吸力怎么样？', '您好，这台是戴森V12 Detect Slim无绳吸尘器。参数：125AW吸力，60分钟续航，1.5kg重量。特点：激光显尘技术（绿色激光照亮灰尘，看清地面脏污）；压电式传感器（感知灰尘大小和数量，分类统计）；LCD屏幕显示实时数据；五层过滤（排出洁净空气）；多种吸头（软绒滚筒、缝隙、床褥、电动刷）。吸力表现：125AW是同价位顶级，可以吸起地板缝隙灰尘、宠物毛发、螨虫。续航60分钟足够清洁120平米房子。机器9成新，电池健康，所有吸头齐全，国行正品。' AS answer, '戴森,V12,吸尘器,吸力,激光' AS tags, '戴森V12吸尘器性能说明' AS source_summary, 87 AS score
  UNION ALL SELECT 'digital_appliance_home', '九阳破壁机噪音大吗？能打冰块吗？', '您好，这台九阳破壁机噪音中等，可以打冰块。参数：1000W功率，35000转/分，1.75L容量。功能：破壁（打破植物细胞壁，释放营养）；加热（煮豆浆、米糊、浓汤）；搅拌（果汁、冰沙、酱料）；研磨（干粉、咖啡豆）。噪音：工作时约75-80分贝，比普通破壁机小（九阳有降噪设计），但仍较吵，建议早上7点后使用。打冰块：可以，但建议加少量水保护刀片。使用建议：食材切块放入；加热功能注意防烫；清洗用自动清洗功能（加水开机搅拌）。机器9成新，刀片无崩口，杯体无裂痕。' AS answer, '九阳,破壁机,噪音,打冰块,加热' AS tags, '九阳破壁机噪音与功能' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_appliance_home', '苏泊尔电压力锅安全吗？压力多大？', '您好，这台苏泊尔电压力锅安全可靠，工作压力50kPa。安全功能：第一，七重安全保护（压力限制、防堵保护、开盖保护、超压保护、限温保护、干烧保护、卸压保护）；第二，数码控温控压，精准控制；第三，可拆内盖，清洗方便；第四，球釜内胆，受热均匀。功能：煮饭、煮粥、煲汤、炖肉、蒸煮、蛋糕等。容量5L，适合3-5口之家。使用建议：食材和水不超过内胆的2/3；排气时远离蒸汽口；开盖前确认压力已完全释放。机器9成新，所有功能正常，密封圈完好。' AS answer, '苏泊尔,电压力锅,安全,压力,球釜' AS tags, '苏泊尔电压力锅安全说明' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_appliance_home', '老板油烟机吸力怎么样？噪音大吗？', '您好，这台老板油烟机吸力强，噪音中等。参数：排风量22立方米/分钟，最大静压400Pa，噪音53分贝。吸力表现：22立方米/分钟属于大吸力，可以快速吸走油烟，适合中式爆炒；400Pa静压可以防止公共烟道倒灌。噪音：53分贝（A声级）属于中等水平，比普通油烟机小一些，但仍有声音。功能：挥手智控（手势开关和调节）；自动清洗（加热溶解油污）；延时关机（关机后继续运转排出余烟）。建议安装高度：距离灶台65-75cm。机器9成新，吸力正常，国行正品。' AS answer, '老板,油烟机,吸力,噪音,静压' AS tags, '老板油烟机吸力与噪音' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_appliance_home', '方太灶台火力多大？能爆炒吗？', '您好，这台方太燃气灶火力5.0kW，可以爆炒。参数：双灶头，左灶5.0kW，右灶4.5kW，熄火保护，童锁保护。火力说明：5.0kW属于大火力，适合爆炒（中式烹饪需要大火快炒）；4.5kW适合煎煮炖。安全功能：熄火保护（意外熄火自动切断燃气）；童锁保护（防止儿童误操作）；防干烧（部分型号）。建议：爆炒用左灶大火；煲汤煮粥用右灶小火；炒菜前预热锅和油。机器9成新，点火正常，火力均匀，国行正品。安装建议请专业人员，注意燃气接口匹配。' AS answer, '方太,灶台,火力,爆炒,安全' AS tags, '方太灶台火力与爆炒' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_appliance_home', '海尔热水器是电的还是燃气的？容量多大？', '您好，这台海尔热水器是电热水器，60L容量。电热水器和燃气热水器区别：电热水器：储水式，60L可以连续洗澡约15-20分钟；安装简单，不需要燃气管道；但有预热时间（约30-60分钟）；体积较大。燃气热水器：即热式，无容量限制，持续出热水；体积小；但需要燃气管道和排烟管；安装复杂。选择建议：有燃气管道选燃气（更方便）；没有燃气选电热（安装简单）。60L适合2-3人连续洗澡。机器9成新，加热正常，保温良好，防电墙功能正常，国行正品。' AS answer, '海尔,热水器,电热,燃气,容量' AS tags, '海尔热水器类型与容量' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_appliance_home', '美的电风扇是落地扇还是塔扇？风力怎么样？', '您好，这台美的电风扇是落地扇，风力强劲。参数：5叶扇叶，3档风力，左右摇头，上下调节，高度可调。落地扇和塔扇区别：落地扇：风力大，覆盖范围广，可调节高度和角度；但占用空间大，有扇叶安全隐患。塔扇：体积小巧，安全（无外露扇叶），送风柔和；但风力较小，覆盖范围窄。选择建议：客厅或大空间选落地扇；卧室或小空间选塔扇。这台落地扇风力3档可调，1档轻柔适合睡觉，3档强劲适合散热。机器9成新，所有功能正常，扇叶无变形，遥控器齐全。' AS answer, '美的,电风扇,落地扇,塔扇,风力' AS tags, '美的电风扇类型与风力' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_appliance_home', '大金空调是变频的吗？省电吗？', '您好，这台大金空调是变频，一级能效，非常省电。大金是日本知名空调品牌，以变频技术和可靠性著称。变频优势：第一，省电：比定频省电约30%；第二，温控精准：温差波动小于0.5度；第三，噪音小：低频运转安静；第四，启动快：快速达到设定温度。一级能效：最高能效等级，APF值高，全年耗电少。大金空调特点：压缩机耐用（10-15年）；静音效果好；制冷制热快速。机器9成新，制冷制热正常，无漏水无异响，国行正品。建议定期清洗滤网保持制冷效果。' AS answer, '大金,空调,变频,省电,一级能效' AS tags, '大金空调变频与省电' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_appliance_home', 'LG电视是OLED还是LED？画质区别？', '您好，这台LG电视是OLED，画质出色。OLED和LED区别：OLED：每个像素自发光，黑色纯净（像素关闭），对比度无限，色彩鲜艳，可视角度大，响应快；但价格贵，有烧屏风险，亮度一般。LED（LCD加LED背光）：亮度高，价格便宜，无烧屏风险；但黑色发灰（背光漏光），对比度有限。选择建议：追求画质选OLED（看电影、玩游戏体验极佳）；预算有限或明亮环境选LED。这台LG OLED 55寸，4K分辨率，支持HDR10和杜比视界，画质出色。机器9成新，屏幕无烧屏无坏点，国行正品。' AS answer, 'LG,OLED,LED,画质,对比度' AS tags, 'LG OLED电视画质说明' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_appliance_home', '三星冰箱是对开门还是十字门？容量多大？', '您好，这台三星冰箱是十字门，容量655L。门型区别：对开门：左右两扇门，左冷冻右冷藏，容量大但取物需开门较大；十字门：上下左右四扇门，分区精细，开门小省电；法式门：上双门下抽屉，冷藏大冷冻抽屉。655L容量适合4-6口之家，可以存一周食材。功能：风冷无霜（不需要除霜）；变频压缩机（省电安静）；多温区控制（冷藏、冷冻、变温区）；制冰功能；智能互联（WiFi控制）。机器9成新，制冷正常，所有门密封良好，国行正品。' AS answer, '三星,冰箱,十字门,容量,风冷' AS tags, '三星冰箱门型与容量' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_appliance_home', '西门子洗衣机洗得干净吗？有烘干功能吗？', '您好，这台西门子洗衣机是洗烘一体机，洗得干净，带烘干功能。参数：10kg洗涤，7kg烘干，1400转脱水，i-Dos自动投放。洗涤性能：多种洗涤程序（棉麻、化纤、羊毛、羽绒服、快洗等）；i-Dos自动投放洗衣液（根据衣物重量和脏污程度自动投放）；除菌洗（高温除菌）。烘干功能：热泵烘干（低温烘干，保护衣物）；7kg烘干容量（小于洗涤容量，建议分批烘）；免晾晒，即洗即穿。机器9成新，洗涤烘干正常，国行正品。建议：烘干时不要超载；定期清理绒毛过滤器。' AS answer, '西门子,洗衣机,洗烘一体,i-Dos,烘干' AS tags, '西门子洗烘一体机性能' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_appliance_home', '家电噪音大吗？会影响休息吗？', '您好，这台家电噪音控制在合理范围，不会影响休息。不同家电噪音：冰箱：约35-42分贝（一级能效更安静），放置平稳可以减少共振；洗衣机：洗涤约50分贝，脱水约70分贝，建议放在浴室或阳台；空调：室内机约25-35分贝（变频更安静），室外机约50分贝；电视：约30分贝（音量决定）。噪音标准：35分贝以下属于安静；40分贝相当于图书馆；50分贝相当于普通对话。建议：家电放在远离卧室的位置；冰箱放置平稳避免共振；空调选择变频低噪音型号；夜间模式降低噪音。机器9成新，噪音正常。' AS answer, '噪音,分贝,冰箱,洗衣机,空调' AS tags, '家电噪音水平说明' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_appliance_home', '家电尺寸多大？能放下吗？', '您好，需要根据具体家电确认尺寸。常见家电尺寸参考：冰箱：双门180L约500x550x1400mm；十字门655L约835x735x1830mm；洗衣机：滚筒10kg约600x600x850mm；空调：室内机约800x280x200mm，室外机约800x600x300mm；电视：55寸约1230x70mm（厚度）；微波炉：23L约500x400x300mm。建议购买前测量安装位置的宽、深、高，留出散热和开门空间。冰箱两侧留5-10cm散热；洗衣机留出进排水管和插手空间；空调室外机留通风空间。机器9成新，尺寸标准，可以告诉我您的安装空间我帮您确认。' AS answer, '尺寸,家电,冰箱,洗衣机,安装' AS tags, '家电尺寸与安装空间' AS source_summary, 81 AS score
  UNION ALL SELECT 'digital_appliance_home', '安装和搬运怎么处理？包安装吗？', '您好，家电安装和搬运分情况说明。安装：大家电（冰箱、洗衣机、空调、电视等）通常不包含安装，需要额外付费。安装费用参考：空调安装约200-400元（含支架、加管等）；热水器安装约150-300元；电视挂墙约100-200元。建议找品牌官方售后安装（专业、有保障），或找当地维修师傅。搬运：大件家电不支持快递，需要物流配送，费用根据距离和体积计算。同城搬楼：有电梯约50-100元/件，无电梯约10-20元/层。建议购买前确认安装和搬运费用，避免超预算。机器9成新，可以协助联系安装师傅。' AS answer, '安装,搬运,家电,空调,费用' AS tags, '家电安装与搬运说明' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_appliance_home', '有保修吗？保修期多久？', '您好，这台家电是国行正品，有官方保修。保修期：整机1-3年（品牌不同），主要部件3-10年。常见家电保修期：冰箱：整机1年，压缩机3-10年；洗衣机：整机1-3年，电机3-10年；空调：整机1-3年，压缩机6-10年；电视：整机1-2年，屏幕3年；微波炉：整机1年。保修方式：到品牌官方售后，凭保修卡和发票即可保修。保修范围：非人为损坏的故障。不保修范围：进水、摔坏、自行拆修、人为损坏、外观磨损。我保留了保修卡和发票，过户后保修不影响。机器9成新，目前无故障。' AS answer, '保修,国行,官方售后,保修卡,压缩机' AS tags, '家电保修期与售后' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_appliance_home', '家电是新的还是二手的？使用多久了？', '您好，这台家电是二手的，使用约1年，9成新。成色说明：外观无磕碰无划痕；功能全部正常；无维修史；无进水。使用痕迹：正常使用产生的轻微痕迹（如手柄处轻微磨亮、按键有轻微使用痕迹），不影响使用。二手家电优势：价格便宜（比新品便宜30-50%）；已经过磨合期（早期故障已暴露）；环保（延长使用寿命）。劣势：无完整包装；保修期可能已过或剩余较少；有使用痕迹。建议购买二手家电选择9成新以上，知名品牌（海尔、美的、格力等），保修期内。机器9成新，欢迎验机。' AS answer, '二手,成色,使用时间,9成新,家电' AS tags, '家电成色与使用说明' AS source_summary, 81 AS score
  UNION ALL SELECT 'digital_appliance_home', '能耗高吗？电费贵吗？', '您好，这台家电能效等级高，电费不贵。能效等级说明：一级能效最省电，三级能效最费电。常见家电耗电：冰箱（一级能效200L）：约0.5度/天，约30度/月；空调（一级能效1.5匹）：制冷约1度/小时，每月约100-200度（看使用频率）；电视（55寸4K）：约0.15度/小时；洗衣机：约0.1度/次；微波炉：约1度/小时。电费计算：以0.6元/度计算，冰箱月电费约18元；空调月电费约60-120元；电视月电费约10元。建议：选一级能效；家电不用时断电；空调温度设置26度。机器9成新，能效标签完好。' AS answer, '能耗,电费,能效等级,省电,耗电' AS tags, '家电能耗与电费说明' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_appliance_home', '能效标签还在吗？怎么看？', '您好，能效标签完好保留。能效标签解读：第一，能效等级：1级（绿色，最省电）到5级（红色，最费电），建议选1级或2级；第二，年耗电量：数字越小越省电，可以直接对比不同型号；第三，产品信息：品牌、型号、容量等；第四，二维码：扫码可以查询更详细信息和真伪。能效标签位置：冰箱、洗衣机贴在机身正面或侧面；空调贴在室内机或说明书；电视贴在机身背面或说明书。建议购买家电时关注能效等级，一级能效虽然贵200-500元，但每年省电费100-300元，长期划算。机器9成新，能效标签完好。' AS answer, '能效标签,能效等级,耗电量,省电,二维码' AS tags, '能效标签解读方法' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_appliance_home', '支持验机吗？家电怎么验？', '您好，支持验机。验机方式：第一，到品牌官方售后检测（免费或少量费用）；第二，找当地家电维修师傅检测；第三，自行检测：开机测试所有功能、检查有无异响、检查制冷制热效果、检查有无漏水、检查遥控器和按键。验机内容：外观有无磕碰划痕；功能是否全部正常；有无维修史；有无进水；能耗是否正常。家电验机重点：冰箱测试制冷和保温；洗衣机测试洗涤和脱水；空调测试制冷和制热；电视测试屏幕有无坏点。机器9成新，欢迎任何方式验机，有问题全额退款。' AS answer, '验机,家电,检测,功能,制冷' AS tags, '家电验机方法与内容' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_appliance_home', '价格还能便宜吗？', '您好，这个价格已经是底价了，相比同款二手市场便宜200-500元。如果您诚心要，我可以再优惠100元，并赠送以下配件：第一，遥控器电池；第二，说明书和保修卡；第三，部分家电送安装配件（如空调支架）。您也知道闲鱼家电利润薄，主要走量。如果是大件家电，可以面交自提，省去物流费。已经是底价了，再低就亏本了，希望您理解。机器9成新，功能正常，性价比很高。如果一次买多件，可以再优惠。' AS answer, '价格,优惠,家电,赠品,自提' AS tags, '家电价格谈判与优惠' AS source_summary, 81 AS score
  UNION ALL SELECT 'digital_appliance_home', '发货怎么发？大件家电怎么运输？', '您好，大件家电运输方式：第一，同城自提：免费，可以当面验货；第二，同城物流：约50-200元（根据体积和距离），送货上门；第三，跨城物流：约200-800元（根据体积和距离），需要到物流点自提或加钱送货上门；第四，德邦物流：大件家电推荐德邦，专业大件运输，可保价。包装方式：原厂包装箱加泡沫加固，确保运输无损。发货前会拍摄视频留证。签收时建议当面验货，确认外观无损、能正常开机后再签收。如有问题可以拒收。机器9成新，欢迎同城自提。' AS answer, '发货,物流,大件,自提,德邦' AS tags, '大件家电运输方式' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_appliance_home', '配件和说明书都齐全吗？', '您好，配件和说明书齐全：原厂包装箱、说明书、保修卡、遥控器（如有）、电源线、进排水管（洗衣机）、支架（空调）等。所有配件都是原厂正品，没有第三方替换。包装箱上的序列号与家电机身序列号一致，可以核对。如果您不需要包装箱，可以省去运费。建议保留原厂包装箱和说明书，以后转手或保修时可能用到。机器9成新，配件几乎全新。部分家电可能缺少原厂包装箱（搬家时丢弃），但说明书和保修卡都保留。' AS answer, '配件,说明书,包装箱,遥控器,保修卡' AS tags, '家电配件与说明书清单' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_appliance_home', '家电用了多久？有维修过吗？', '您好，这台家电使用约1年，没有维修过。使用情况说明：第一，使用频率正常（家庭日常使用，非商用）；第二，定期保养（如空调清洗滤网、冰箱除霜）；第三，无维修史，所有部件原厂；第四，无进水无摔落；第五，功能全部正常。判断家电是否维修过方法：第一，看螺丝有无拧痕；第二，看接缝是否均匀；第三，到官方售后查询维修记录；第四，外观有无更换部件痕迹。机器9成新，无维修史，欢迎任何方式验机。建议购买二手家电选择无维修、知名品牌、保修期内的。' AS answer, '使用时间,维修,保养,家电,验机' AS tags, '家电使用与维修历史' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_appliance_home', '家电怎么清洁保养？需要定期维护吗？', '您好，家电需要定期清洁保养，可以延长使用寿命。清洁保养方法：冰箱：每周擦拭内壁，每月清洗密封条，每季度清理冷凝器灰尘（背面或底部），每年除霜一次（直冷型）；洗衣机：每月用洗衣机清洁剂高温空转清洗内筒，每次用后开门通风晾干，定期清理过滤网；空调：每两周清洗滤网（清水冲洗晾干），每年清洗蒸发器和冷凝器（建议请专业人员），冬季不用时罩住室内机；电视：每周用超纤布干擦屏幕，避免使用酒精等溶剂，不用时关闭电源；微波炉：每次用后擦拭内壁，每月水加柠檬片加热5分钟去味。机器9成新，保养良好，欢迎验机。' AS answer, '清洁,保养,维护,家电,除菌' AS tags, '家电清洁保养方法' AS source_summary, 82 AS score
) q
JOIN ai_cs_kb_category c ON c.code = q.code AND c.deleted = 0 AND c.parent_id IS NOT NULL;


-- ----------------------------------------------------------------------------
-- 6. digital_smart（智能设备）- 30 条
-- ----------------------------------------------------------------------------
INSERT IGNORE INTO ai_cs_learned_kb (
    category_id, question, answer, tags, source_summary,
    content_hash, score, review_status, enabled, vector_indexed,
    source_count, source_conv_ids, learn_batch_id, sensitive_filtered,
    source_type, deleted, created_time, updated_time
)
SELECT c.id, q.question, q.answer, q.tags, q.source_summary,
       MD5(CONCAT(q.question, q.answer)), q.score, 'approved', 1, 1,
       1, NULL, 'seed-v1.52', 1, 'seed', 0, NOW(), NOW()
FROM (
  SELECT 'digital_smart' AS code, 'Apple Watch是几代？兼容安卓吗？' AS question, '您好，这台是Apple Watch Series 9，45mm，GPS加蜂窝网络版。兼容性：Apple Watch只能配对iPhone使用，不兼容安卓手机。如果您是安卓用户，建议选华为手表或小米手环。Series 9主要功能：心率监测、血氧检测、ECG心电图、睡眠监测、运动追踪、跌倒检测、车祸检测、SOS紧急联络。续航约18小时（重度使用）到36小时（低电量模式）。支持蜂窝网络，可以独立打电话和发短信。机器9成新，表带和充电器齐全，国行正品。' AS answer, 'AppleWatch,Series9,兼容性,安卓,iPhone' AS tags, 'Apple Watch兼容性与功能说明' AS source_summary, 88 AS score
  UNION ALL SELECT 'digital_smart', '华为手表GT4续航多久？能独立通话吗？', '您好，华为Watch GT4续航非常长，常规使用约14天，重度使用约7天。是否独立通话：标准版不支持独立通话（没有eSIM），只有蓝牙通话（连接手机后可以接听电话）；如果需要独立通话，选Watch 4 Pro或Watch GT4 eSIM版。GT4主要功能：心率、血氧、睡眠、压力监测；100多种运动模式；蓝牙通话；消息通知；NFC公交门禁；GPS定位。兼容性：安卓和iPhone都可以配对，但iPhone上部分功能受限（如NFC、微信回复）。机器9成新，国行正品，表带和充电器齐全。' AS answer, '华为GT4,续航,通话,eSIM,兼容' AS tags, '华为GT4续航与通话功能' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_smart', '小米手环8功能多吗？值得买吗？', '您好，小米手环8功能丰富，性价比很高，值得买。主要功能：1.62寸AMOLED屏幕，显示效果好；心率、血氧、睡眠监测；150种运动模式；NFC公交门禁（NFC版）；蓝牙通话；消息通知；遥控拍照；音乐控制。续航约16天，充电约1小时。兼容性：安卓和iPhone都可以配对，但iPhone上部分功能受限。和小米手环7区别：屏幕更大更亮；新增跑步模式；续航提升；表带拆卸更方便。价格约200-250元（标准版），NFC版约250-300元。机器9成新，国行正品，配件齐全。如果您预算有限，手环8是最佳选择。' AS answer, '小米手环8,功能,性价比,NFC,续航' AS tags, '小米手环8功能与性价比' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_smart', '小天才手表能打电话吗？需要插卡吗？', '您好，小天才手表可以打电话，需要插SIM卡。小天才电话手表主要功能：4G通话（需要插入nano-SIM卡）；视频通话；GPS定位（家长可以查看孩子位置）；SOS一键求救；上课禁用模式（家长设置上课时间免打扰）；微聊（手表间发消息）；运动监测。适用人群：5-12岁儿童。SIM卡要求：移动联通电信都支持，建议选大流量套餐（视频通话耗流量）。资费：手表本身约500-1500元，每月话费约30-50元。机器9成新，国行正品，充电器和表带齐全。家长需要下载小天才APP绑定管理。' AS answer, '小天才,电话手表,插卡,4G,定位' AS tags, '小天才手表通话与插卡说明' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_smart', '小度音箱能控制家电吗？需要什么条件？', '您好，小度音箱可以控制智能家居，需要满足以下条件：第一，家电支持智能控制（WiFi或蓝牙连接）；第二，家电品牌支持小度生态（如小米、涂鸦、欧瑞博等）；第三，家电已添加到小度APP。控制方式：语音控制（小度小度，打开空调）；APP控制（手机远程控制）；场景联动（回家模式自动开灯开空调）。支持的家电：灯泡、插座、空调、电视、扫地机器人、窗帘等。小度音箱本身功能：播放音乐、查天气、设闹钟、讲故事、百科问答。机器9成新，国行正品，电源线齐全。' AS answer, '小度音箱,智能家居,语音控制,家电,场景' AS tags, '小度音箱控制家电说明' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_smart', '天猫精灵和小度哪个好？音质怎么样？', '您好，天猫精灵和小度各有优势。天猫精灵优势：音质较好（部分型号采用丹拿调音）；阿里生态（淘宝购物、支付宝）；智能家居控制（支持阿里智能生态）；声音识别准确。小度优势：百度搜索能力强，知识问答丰富；儿童模式内容多（绘本、教育）；智能家居生态广（支持米家等）；价格便宜。选择建议：注重音质选天猫精灵（IN灵犀系列）；注重智能和教育选小度；注重智能家居控制看您家现有设备生态。我手里这台是天猫精灵IN灵犀，音质不错，9成新，国行正品。' AS answer, '天猫精灵,小度,音质,智能,对比' AS tags, '天猫精灵与小度对比' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_smart', 'HomePod支持安卓吗？只能配对苹果吗？', '您好，HomePod只支持苹果生态，不兼容安卓。HomePod特点：第一，配对：只能与iPhone、iPad配对，需要Apple Music或iCloud账号；第二，音质：HomePod mini音质在同价位出色，计算音频技术自动调音；第三，智能家居：支持HomeKit设备控制（通过家庭APP）；第四，Siri：语音助手功能，可以控制播放、查天气、发消息等；第五，隔空播放：苹果设备间音频无缝切换。如果您是苹果全家桶用户，HomePod体验最佳；如果是安卓用户，选小度或天猫精灵。机器9成新，国行正品，电源线齐全。' AS answer, 'HomePod,安卓,苹果,配对,Siri' AS tags, 'HomePod兼容性与配对说明' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_smart', '小米智能家居怎么搭？需要什么设备？', '您好，小米智能家居搭建步骤：第一，核心设备：小米网关（或小爱音箱带网关功能），负责连接子设备；第二，控制中心：小爱音箱（语音控制）或小米手机（APP控制）；第三，智能设备：智能灯泡、智能插座、智能门锁、智能窗帘、扫地机器人、空气净化器等；第四，传感器：人体传感器、门窗传感器、温湿度传感器（用于自动化联动）；第五，场景设置：回家模式（开灯开空调）、离家模式（关灯关电）、睡眠模式（关灯关窗帘）。建议从基础套装开始（网关加灯泡加插座），逐步扩展。机器9成新，国行正品。' AS answer, '小米,智能家居,网关,场景,传感器' AS tags, '小米智能家居搭建指南' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_smart', '平衡车能骑多久？续航多少公里？', '您好，这台平衡车续航约20-25公里，骑行时间约2-3小时。参数：双电机350W，最大速度15km/h，载重100kg，充电时间约2-3小时。续航影响因素：第一，体重（越重越费电）；第二，路面（上坡、颠簸路面费电）；第三，速度（高速骑行费电）；第四，温度（低温电池性能下降）；第五，使用习惯（频繁启停费电）。安全建议：佩戴头盔护具；初学者先在空旷平地练习；雨天不要骑行（电子部件怕水）；不要在机动车道骑行。机器9成新，电池健康，轮胎无磨损，国行正品。适合短途代步和娱乐。' AS answer, '平衡车,续航,公里,安全,电池' AS tags, '平衡车续航与安全说明' AS source_summary, 81 AS score
  UNION ALL SELECT 'digital_smart', '扫地机器人好用吗？能扫干净吗？', '您好，这台扫地机器人很好用，能扫干净。参数：激光导航，4000Pa吸力，电控水箱（扫拖一体），续航180分钟，APP远程控制。清洁能力：4000Pa吸力可以吸走灰尘、毛发、颗粒物；拖地功能可以擦除轻度污渍；激光导航精准建图，不漏扫不重复；自动回充，断点续扫。适合：硬地板、瓷砖、低毛地毯。不适合：长毛地毯、有台阶的房间。建议：使用前先清理地面杂物；定期清理尘盒和滤网；拖地时及时加水。机器9成新，所有配件齐全（边刷、滤网、拖布），国行正品。' AS answer, '扫地机器人,清洁,导航,扫拖,吸力' AS tags, '扫地机器人清洁能力说明' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_smart', '智能门锁安全吗？指纹解锁灵敏吗？', '您好，这台智能门锁安全可靠，指纹解锁灵敏。安全功能：第一，半导体指纹识别（比光学更安全，防假指纹），识别率99%，0.5秒解锁；第二，C级锁芯（最高安全等级，防技术开锁270分钟以上）；第三，多重开锁方式（指纹、密码、IC卡、钥匙、APP）；第四，防撬报警（异常开锁自动报警）；第五，虚位密码（正确密码前后输入乱码，防偷窥）。指纹解锁特点：360度识别，湿手也可以；支持100个指纹；老人小孩指纹都能识别。机器9成新，国行正品，安装需要专业人员。建议保留机械钥匙备用。' AS answer, '智能门锁,指纹,安全,C级锁芯,报警' AS tags, '智能门锁安全与指纹解锁' AS source_summary, 87 AS score
  UNION ALL SELECT 'digital_smart', '智能灯泡能调色温吗？需要网关吗？', '您好，这台智能灯泡支持调色温和亮度。参数：WiFi连接（不需要网关），2700K-6500K色温调节（暖光到冷白光），1%-100%亮度调节，10W功率，800流明。控制方式：第一，APP控制（米家APP或涂鸦APP），远程开关、调光调色；第二，语音控制（小爱同学、小度、天猫精灵）；第三，场景模式（阅读模式暖光、工作模式冷白光、影院模式昏暗）；第四，定时开关（自动开关灯）；第五，分组控制（多个灯泡一组同时控制）。WiFi直连不需要网关，比蓝牙版更方便。机器9成新，国行正品，9W功率节能。' AS answer, '智能灯泡,色温,网关,WiFi,调光' AS tags, '智能灯泡色温调节与连接' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_smart', '智能插座能定时吗？能统计用电量吗？', '您好，这台智能插座支持定时和用电量统计。功能：第一，定时开关（设置自动开关时间，如晚上10点关饮水机）；第二，用电量统计（实时功率和历史用电量，帮您发现耗电设备）；第三，远程控制（手机APP远程开关，出门忘关电可以远程关）；第四，语音控制（小爱同学、小度等语音开关）；第五，过载保护（超过额定功率自动断电，保护安全）。参数：WiFi连接，10A最大电流（2200W），适用于电热水壶、饮水机、台灯、电暖器等。机器9成新，国行正品。建议：大功率电器（空调、热水器）选16A版本。' AS answer, '智能插座,定时,用电量,远程,过载' AS tags, '智能插座定时与用电统计' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_smart', '智能摄像头能存几天录像？需要内存卡吗？', '您好，这台智能摄像头支持本地存储和云存储。本地存储：TF卡（Class10以上），32G约存3-5天，64G约存7-10天，128G约存15-20天（循环覆盖）；云存储：需要订阅云服务，7天循环约15元/月，30天循环约30元/月。参数：2K分辨率，红外夜视，人形检测，双向语音，360度旋转，移动追踪。使用建议：第一，选择Class10以上的TF卡保证写入速度；第二，开启移动检测报警，有人移动自动推送通知；第三，隐私模式（在家时可以关闭摄像头）；第四，定期格式化TF卡延长寿命。机器9成新，国行正品，不含TF卡。' AS answer, '智能摄像头,存储,内存卡,云存储,录像' AS tags, '智能摄像头存储与录像说明' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_smart', '智能手表续航多久？需要每天充电吗？', '您好，智能手表续航因品牌型号不同：Apple Watch Series 9约18-36小时（需要每天充电）；华为Watch GT4约7-14天（不需要每天充电）；小米手表S3约7-15天；小天才Z9约2-3天。续航影响因素：第一，使用频率（频繁查看消息、运动监测费电）；第二，屏幕亮度（越亮越费电）；第三，功能开启（GPS、心率、血氧持续监测费电）；第四，通知频率（频繁振动费电）；第五，温度（低温电池性能下降）。建议：不需要功能可以关闭（如全天心率监测改为定时）；夜间可以开启 theater mode；电量低于20%及时充电。机器9成新，电池健康。' AS answer, '智能手表,续航,充电,电池,省电' AS tags, '智能手表续航与充电说明' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_smart', '智能设备需要下载APP吗？不下载能用吗？', '您好，大部分智能设备需要下载APP才能完整使用。需要APP的原因：第一，配对连接（设备首次使用需要APP引导配对）；第二，功能设置（定时、场景、自动化等需要在APP中设置）；第三，固件升级（通过APP更新设备固件修复Bug和增加功能）；第四，远程控制（不在家也能控制设备）；第五，数据查看（如摄像头录像、手环健康数据）。不下载APP的替代方式：部分设备支持语音控制（如小爱音箱控制智能灯泡，不需要单独APP）；部分设备有物理开关可以基本使用。建议：下载APP获得完整体验。机器9成新，国行正品，APP免费下载。' AS answer, 'APP,智能设备,配对,远程控制,固件' AS tags, '智能设备APP使用说明' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_smart', '国行和水货智能手表有什么区别？', '您好，国行和水货智能手表主要区别：第一，保修：国行全国联保1年，水货无官方保修；第二，功能：部分功能在国内受限（如Apple Watch的ECG心电图功能国行已支持，水货可能不支持或需要切换地区）；第三，语言：国行支持中文，水货可能需要设置；第四，充电器：国行是国标插头，水货可能需要转接头；第五，价格：水货通常便宜200-800元；第六，蜂窝网络：国行eSIM支持三大运营商，水货可能不兼容。选择建议：Apple Watch买国行（功能完整、保修方便）；华为手表买国行（水货较少）。我手里这台是国行正品，发票齐全。' AS answer, '国行,水货,智能手表,保修,功能' AS tags, '国行与水货智能手表差异' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_smart', '智能手表能测血压吗？准吗？', '您好，部分智能手表支持血压监测，但准确度有限。支持血压监测的手表：华为Watch D（气泵式，医疗级准确度）；华为Watch 4（光学估算，参考值）；三星Galaxy Watch 4以上（光学估算，需要校准）。准确度：气泵式（华为Watch D）最准，可以达到医疗级；光学估算只是参考值，不能替代医疗设备。使用建议：第一，定期用传统血压计校准；第二，测量时保持安静坐姿，手表与心脏同高；第三，血压异常建议就医，不要仅依赖手表数据；第四，高血压患者建议配备传统血压计。我手里这台是华为Watch D，气泵式血压监测，9成新，国行正品。' AS answer, '智能手表,血压,准确度,华为WatchD,医疗' AS tags, '智能手表血压监测准确性' AS source_summary, 85 AS score
  UNION ALL SELECT 'digital_smart', '智能设备能和手机配对吗？怎么连接？', '您好，智能设备可以和手机配对，连接方式：第一，蓝牙配对：打开手机蓝牙，搜索设备，点击配对（适用于手环、手表、耳机等低功耗设备）；第二，WiFi配对：设备进入配对模式，手机APP搜索设备，按提示连接WiFi（适用于摄像头、音箱、扫地机等）；第三，扫码配对：设备显示二维码或APP扫描设备二维码（部分智能设备）；第四，NFC碰一碰：手机NFC触碰设备NFC区域自动配对（华为、小米部分设备）。配对要求：手机系统版本兼容（iOS或安卓版本要求）；下载对应APP；设备处于配对模式。机器9成新，连接正常。' AS answer, '配对,蓝牙,WiFi,扫码,NFC' AS tags, '智能设备手机配对连接方法' AS source_summary, 81 AS score
  UNION ALL SELECT 'digital_smart', '有保修吗？保修期多久？', '您好，这台智能设备是国行正品，有官方保修。保修期：整机1年（部分品牌2年）。保修方式：到品牌官方售后服务中心（苹果、华为、小米等全国都有），凭保修卡和发票即可保修。保修范围：非人为损坏的故障（如电池故障、主板问题、屏幕失灵）。不保修范围：进水（非防水型号）、摔坏、自行拆修、人为损坏、表带磨损（属于耗材）。我保留了原厂包装盒、保修卡、发票，过户后保修不影响。机器9成新，目前无任何故障，所有功能正常。建议到货后到官方查询保修状态。' AS answer, '保修,国行,官方售后,保修卡,发票' AS tags, '智能设备保修期与售后' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_smart', '怎么辨别智能设备真假？担心买到高仿', '您好，辨别智能设备真假方法：第一，序列号：包装盒、机身、APP中三处序列号必须一致，到品牌官网查询；第二，连接动画：正品有品牌专属连接动画（Apple Watch、华为手表等），高仿可能没有或粗糙；第三，功能：正品功能完整（ECG、血氧、GPS等），高仿可能缺失部分功能；第四，做工：正品接缝均匀、材质质感好，高仿做工粗糙；第五，APP识别：正品可以在品牌官方APP中识别并显示完整信息，高仿可能无法识别或显示异常；第六，官方售后检测：最权威的方式。我手里这台是国行正品，欢迎任何方式验机。' AS answer, '真假,高仿,序列号,验机,功能' AS tags, '智能设备真假辨别方法' AS source_summary, 86 AS score
  UNION ALL SELECT 'digital_smart', '成色怎么样？有磨损吗？', '您好，这台智能设备9成新，使用约半年，有轻微使用痕迹但无磕碰无划痕。具体成色：表盘无划痕（贴膜保护）；表带有轻微使用痕迹（正常佩戴）；金属外壳无磕碰无凹陷；充电触点干净无氧化；按键灵敏回弹正常；屏幕显示完美无坏点。功能全部正常：蓝牙连接稳定、心率监测准确、GPS定位正常、续航正常。如果您对成色要求极高，我手里还有一台95新的同款，价格贵100元。建议购买二手智能设备选择9成新以上，性价比和成色平衡较好。机器9成新，欢迎到货验机。' AS answer, '成色,9成新,磨损,表盘,表带' AS tags, '智能设备成色与磨损说明' AS source_summary, 81 AS score
  UNION ALL SELECT 'digital_smart', '配件齐全吗？送什么？', '您好，配件齐全：原厂包装盒、智能设备主体、充电器（磁吸或无线充电底座）、说明书、保修卡。我额外赠送：保护壳一个（适用于带屏设备）、屏幕贴膜一张、收纳袋一个。所有配件都是原厂正品，没有第三方替换（除赠送品外）。包装盒序列号与设备一致，可以核对。如果您不需要配件只要裸机，我可以优惠50元。机器9成新，配件几乎全新。建议保留原厂包装盒，以后转手或保修时可能用到。设备功能全部正常，欢迎到货验机。' AS answer, '配件,原装,充电器,包装盒,赠品' AS tags, '智能设备配件清单与赠品' AS source_summary, 80 AS score
  UNION ALL SELECT 'digital_smart', '价格还能便宜吗？送什么？', '您好，这个价格已经是底价了，相比同款二手市场便宜100-200元。如果您诚心要，我可以再优惠50元，并赠送以下配件：第一，保护壳一个；第二，屏幕贴膜一张；第三，收纳袋一个；第四，充电线一根。这样下来比市场便宜200-300元了。您也知道闲鱼数码利润薄，主要走量。如果走验机服务，验机费20元我承担。已经是底价了，再低就亏本了，希望您理解。设备9成新，功能正常，性价比很高。如果您一次买多件，可以再优惠。' AS answer, '价格,优惠,赠品,保护壳,验机' AS tags, '智能设备价格谈判与赠品' AS source_summary, 81 AS score
  UNION ALL SELECT 'digital_smart', '支持验机吗？怎么验？', '您好，支持验机。验机方式：第一，闲鱼验机服务（部分城市支持），下单时选择；第二，到品牌官方售后检测；第三，自行检测：检查外观、序列号核对、配对连接测试、功能测试（心率、GPS、NFC等）、续航测试、充电测试、屏幕检查（有无坏点）、按键测试。验机内容：配置是否与描述一致、有无拆修、有无进水、功能是否正常、电池健康度。智能设备验机重点：传感器是否准确（心率、血氧）、GPS定位是否正常、连接是否稳定、充电是否正常。机器9成新，欢迎任何方式验机，有问题全额退款。' AS answer, '验机,序列号,功能,传感器,电池' AS tags, '智能设备验机方法与内容' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_smart', '发货用什么快递？包装安全吗？', '您好，智能设备属于小型数码，默认发顺丰快递，包邮（偏远地区除外）。包装方式：原厂包装盒加气泡膜加顺丰专用小箱，确保运输无损。发货前会拍摄视频留证，包括设备外观、序列号、配件、包装过程。签收时建议您当面验货，确认外观无损、能正常开机配对后再签收。如有问题可以拒收并联系我。发货时间一般是付款后24小时内，节假日顺延。如果不接受顺丰，可以发中通圆通，邮费同样我承担。机器9成新，欢迎到货验机。' AS answer, '顺丰,包邮,包装,发货,验货' AS tags, '智能设备快递发货说明' AS source_summary, 79 AS score
  UNION ALL SELECT 'digital_smart', '智能设备防水吗？能戴着游泳吗？', '您好，智能设备防水等级不同，需要看具体型号。防水等级说明：IPX4：防泼溅（雨水、汗水，不能浸泡）；IPX7：1米水深30分钟（意外落水，不建议游泳）；IPX8：可以持续浸泡（适合游泳，具体深度看厂家标称）。常见设备防水等级：Apple Watch Series 9：50米防水（可以游泳和浅潜）；华为Watch GT4：50米防水；小米手环8：50米防水；AirPods Pro：IPX4（只能防泼溅，不能游泳）。游泳建议：确认设备支持50米防水以上；游泳后用淡水冲洗（避免泳池氯气腐蚀）；热水浴和蒸汽浴不建议佩戴（水蒸气会进入）；定期检查防水胶圈老化。机器9成新，防水性能正常。' AS answer, '防水,IP68,游泳,智能手表,等级' AS tags, '智能设备防水等级与游泳' AS source_summary, 83 AS score
  UNION ALL SELECT 'digital_smart', '智能手表能回复微信吗？怎么操作？', '您好，智能手表可以回复微信，但功能因品牌和系统不同。Apple Watch：可以查看微信消息、语音回复、快捷文字回复、语音转文字、发送表情；不支持键盘输入和发送图片。华为手表（鸿蒙系统）：可以查看消息、语音回复、快捷文字、语音转文字；部分型号支持手写输入和键盘（输入体验有限）。小米手表：可以查看消息、语音回复、快捷文字。使用方法：手表收到微信通知后，点击消息进入回复界面，选择语音、文字或快捷回复。限制：回复内容较短，不适合长对话；需要手表和手机保持蓝牙连接；部分功能需要手机端微信在后台运行。机器9成新，微信回复功能正常。' AS answer, '微信,回复,智能手表,语音,键盘' AS tags, '智能手表回复微信功能' AS source_summary, 82 AS score
  UNION ALL SELECT 'digital_smart', '智能门锁电池能用多久？没电了怎么办？', '您好，智能门锁电池续航约8-12个月，没电了有应急方案。电池续航：8节AA电池（5号）约8-12个月（使用频率影响），锂电池约6-12个月。低电量提醒：电量低于20%时手表和APP推送提醒，低于10%时每次开门都会语音提醒。没电了应急方案：第一，应急电源：门锁底部有Micro-USB或Type-C接口，可以用充电宝临时供电开门；第二，机械钥匙：每把锁配3把机械钥匙，钥匙孔在前面板下方或侧面隐藏设计；第三，蓝牙开门：部分型号支持手机蓝牙开门（不需要电池供电，手机供电）。建议：听到低电量提醒及时更换电池；备用钥匙放在可靠的地方（如车里、办公室）；不要等完全没电再换。机器9成新，电池续航正常。' AS answer, '门锁,电池,续航,充电,应急' AS tags, '智能门锁电池续航与应急' AS source_summary, 84 AS score
  UNION ALL SELECT 'digital_smart', '智能手环能监测睡眠吗？准确吗？', '您好，智能手环可以监测睡眠，准确度中上。监测原理：通过加速度计（检测体动）、心率传感器（检测心率变化）、血氧传感器（部分型号）综合分析睡眠阶段（浅睡、深睡、REM、清醒）。准确度：与专业睡眠监测设备（多导睡眠仪）对比，手环准确度约80-85%，可以反映睡眠趋势和大致结构，但不能作为医疗诊断。监测内容：入睡时间、起床时间、总睡眠时长、睡眠阶段分布（浅睡、深睡、REM比例）、睡眠评分、呼吸暂停风险（部分型号）。使用建议：佩戴位置正确（手腕上方，紧贴皮肤）；保持电量充足；睡前佩戴，醒后查看数据；长期跟踪趋势比单次数据更有意义。机器9成新，睡眠监测正常。' AS answer, '睡眠,监测,手环,准确,数据' AS tags, '智能手环睡眠监测准确性' AS source_summary, 82 AS score
) q
JOIN ai_cs_kb_category c ON c.code = q.code AND c.deleted = 0 AND c.parent_id IS NOT NULL;