-- V1.74 工作流教学知识库
-- 为系统客服"小梦"配置完整的工作流教学知识库，覆盖所有节点能力、默认工作流说明、常见刁钻问题。
-- 注意：content 字段内不得使用 ASCII 分号（半角分号），统一使用中文分号（全角分号），因为 SchemaCompatibilityRunner 按半角分号分割语句。
-- 本文件由 SchemaCompatibilityRunner.seedAiCsKnowledgeBaseFromMigrationV1_74() 幂等执行。

-- 1. 工作流基础概念与默认工作流说明
INSERT INTO ai_cs_knowledge(tenant_id, category, title, content, keywords, priority, enabled, sort_order, created_time, updated_time)
SELECT NULL, 'workflow_teaching', '工作流基础概念与默认工作流',
'工作流是闲鱼助手的自动化流程引擎，可以把多个操作步骤串联起来自动执行。一个工作流由多个节点组成，节点之间用连线串联，数据从上游节点流向下游节点。\n\n系统为每位新用户默认配置了一条【商品搜索工作流】，开箱即用。这条工作流的功能：根据你输入的关键词自动采集闲鱼商品，使用 image-2 模型为每个商品生成 AI 封面图，然后自动发布到你选择的闲鱼账号。\n\n默认工作流的节点链路：触发器(选账号) → 商品获取(关键词搜索) → 商品筛选(默认关闭) → 润色文案(默认关闭) → 生图节点(image-2) → 发布节点。\n\n核心公式：商品数量配置 × 发布账号数 = 最终实际发布商品数量。例如配置采集 5 个商品 + 选择 2 个账号 = 实际发布 10 个商品。\n\n你可以在【工作流】页面修改默认工作流的配置，也可以新建自己的工作流。',
'工作流,默认工作流,商品搜索工作流,基础概念,节点,连线,流程', 200, 1, 100, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM ai_cs_knowledge WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='工作流基础概念与默认工作流');

UPDATE ai_cs_knowledge SET content='工作流是闲鱼助手的自动化流程引擎，可以把多个操作步骤串联起来自动执行。一个工作流由多个节点组成，节点之间用连线串联，数据从上游节点流向下游节点。\n\n系统为每位新用户默认配置了一条【商品搜索工作流】，开箱即用。这条工作流的功能：根据你输入的关键词自动采集闲鱼商品，使用 image-2 模型为每个商品生成 AI 封面图，然后自动发布到你选择的闲鱼账号。\n\n默认工作流的节点链路：触发器(选账号) → 商品获取(关键词搜索) → 商品筛选(默认关闭) → 润色文案(默认关闭) → 生图节点(image-2) → 发布节点。\n\n核心公式：商品数量配置 × 发布账号数 = 最终实际发布商品数量。例如配置采集 5 个商品 + 选择 2 个账号 = 实际发布 10 个商品。\n\n你可以在【工作流】页面修改默认工作流的配置，也可以新建自己的工作流。', keywords='工作流,默认工作流,商品搜索工作流,基础概念,节点,连线,流程', updated_time=NOW() WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='工作流基础概念与默认工作流';

-- 2. 触发器节点 TRIGGER 详解
INSERT INTO ai_cs_knowledge(tenant_id, category, title, content, keywords, priority, enabled, sort_order, created_time, updated_time)
SELECT NULL, 'workflow_teaching', '触发器节点(TRIGGER)详解',
'触发器是工作流的起点，每个工作流必须有且仅有一个触发器节点。\n\n配置参数：\n• 发布账号(selectedAccountIds)：多选，选择一个或多个闲鱼账号作为发布目标。这是核心参数，决定最终商品发布到哪些账号。\n• 执行次数(executeCount)：默认 1，一般不需要修改。\n\n重要说明：\n1. 必须选择至少一个账号才能运行工作流，否则预检会报错。\n2. 选择的账号必须是 Cookie 有效的登录状态，否则运行会失败。\n3. 多账号的含义：工作流会为每个账号都执行一遍完整的采集→生图→发布流程，所以最终发布数量 = 商品数量 × 账号数量。\n4. 如果只选了一个账号，最终发布数量 = 商品数量 × 1 = 商品数量。\n\n常见问题：\nQ：为什么我选了 2 个账号但只发布了 5 个商品？\nA：请检查商品数量配置(targetCount)，如果配置为 5 且选了 2 个账号，应该发布 10 个。如果只发布了 5 个，可能是某个账号 Cookie 失效或发布失败，请查看执行日志。',
'触发器,TRIGGER,账号,发布账号,执行次数,selectedAccountIds', 200, 1, 101, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM ai_cs_knowledge WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='触发器节点(TRIGGER)详解');

UPDATE ai_cs_knowledge SET content='触发器是工作流的起点，每个工作流必须有且仅有一个触发器节点。\n\n配置参数：\n• 发布账号(selectedAccountIds)：多选，选择一个或多个闲鱼账号作为发布目标。这是核心参数，决定最终商品发布到哪些账号。\n• 执行次数(executeCount)：默认 1，一般不需要修改。\n\n重要说明：\n1. 必须选择至少一个账号才能运行工作流，否则预检会报错。\n2. 选择的账号必须是 Cookie 有效的登录状态，否则运行会失败。\n3. 多账号的含义：工作流会为每个账号都执行一遍完整的采集→生图→发布流程，所以最终发布数量 = 商品数量 × 账号数量。\n4. 如果只选了一个账号，最终发布数量 = 商品数量 × 1 = 商品数量。\n\n常见问题：\nQ：为什么我选了 2 个账号但只发布了 5 个商品？\nA：请检查商品数量配置(targetCount)，如果配置为 5 且选了 2 个账号，应该发布 10 个。如果只发布了 5 个，可能是某个账号 Cookie 失效或发布失败，请查看执行日志。', keywords='触发器,TRIGGER,账号,发布账号,执行次数,selectedAccountIds', updated_time=NOW() WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='触发器节点(TRIGGER)详解';

-- 3. 商品获取节点 PRODUCT_FETCH 详解
INSERT INTO ai_cs_knowledge(tenant_id, category, title, content, keywords, priority, enabled, sort_order, created_time, updated_time)
SELECT NULL, 'workflow_teaching', '商品获取节点(PRODUCT_FETCH)详解',
'商品获取节点负责从闲鱼采集商品数据，是工作流的数据源头。\n\n两种获取方式(sourceType)：\n1. 关键词搜索(keyword)：输入关键词，系统通过闲鱼搜索 API 采集商品。支持多关键词，每个关键词都会搜索并汇总结果。搜索模式支持快速(直调API)和慢速(浏览器拦截)两种，系统会自动选择最稳定的方式。\n2. 店铺搜索(shop)：输入店铺链接，系统通过浏览器爬取该店铺的所有商品。\n\n配置参数：\n• 获取方式(sourceType)：keyword 或 shop\n• 关键词(keywords)：关键词数组，sourceType=keyword 时使用\n• 店铺链接(shopUrl)：sourceType=shop 时使用\n• 目标商品数量(targetCount)：1-100，本次要采集多少个商品\n• 获取模式(fetchMode)：random(随机) / top(优先热门) / newest(优先最新)\n\n重要说明：\n1. targetCount 是每个账号采集的商品数量，不是总数量。选 2 个账号 + targetCount=5 = 采集 10 个商品(每个账号 5 个)。\n2. 如果开启了商品筛选且筛选后数量不足，系统会自动回到本节点重新采集更多商品(最多重试 5 次)。\n3. 关键词搜索可能触发闲鱼风控(Baxia)，系统会自动降级到浏览器慢速搜索。\n4. 店铺搜索必须通过浏览器进行，速度较慢但更稳定。\n\n常见问题：\nQ：targetCount 设为 100 但只采集到 20 个怎么办？\nA：闲鱼搜索结果有限，某些关键词可能只有 20 个结果。可以尝试换更热门的关键词，或减少 targetCount。\nQ：关键词搜索和店铺搜索有什么区别？\nA：关键词搜索是从闲鱼全站搜索商品，店铺搜索是爬取指定店铺的商品。关键词搜索更快但可能触发风控，店铺搜索更慢但更稳定。',
'商品获取,PRODUCT_FETCH,关键词,店铺,搜索,targetCount,采集', 200, 1, 102, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM ai_cs_knowledge WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='商品获取节点(PRODUCT_FETCH)详解');

UPDATE ai_cs_knowledge SET content='商品获取节点负责从闲鱼采集商品数据，是工作流的数据源头。\n\n两种获取方式(sourceType)：\n1. 关键词搜索(keyword)：输入关键词，系统通过闲鱼搜索 API 采集商品。支持多关键词，每个关键词都会搜索并汇总结果。搜索模式支持快速(直调API)和慢速(浏览器拦截)两种，系统会自动选择最稳定的方式。\n2. 店铺搜索(shop)：输入店铺链接，系统通过浏览器爬取该店铺的所有商品。\n\n配置参数：\n• 获取方式(sourceType)：keyword 或 shop\n• 关键词(keywords)：关键词数组，sourceType=keyword 时使用\n• 店铺链接(shopUrl)：sourceType=shop 时使用\n• 目标商品数量(targetCount)：1-100，本次要采集多少个商品\n• 获取模式(fetchMode)：random(随机) / top(优先热门) / newest(优先最新)\n\n重要说明：\n1. targetCount 是每个账号采集的商品数量，不是总数量。选 2 个账号 + targetCount=5 = 采集 10 个商品(每个账号 5 个)。\n2. 如果开启了商品筛选且筛选后数量不足，系统会自动回到本节点重新采集更多商品(最多重试 5 次)。\n3. 关键词搜索可能触发闲鱼风控(Baxia)，系统会自动降级到浏览器慢速搜索。\n4. 店铺搜索必须通过浏览器进行，速度较慢但更稳定。\n\n常见问题：\nQ：targetCount 设为 100 但只采集到 20 个怎么办？\nA：闲鱼搜索结果有限，某些关键词可能只有 20 个结果。可以尝试换更热门的关键词，或减少 targetCount。\nQ：关键词搜索和店铺搜索有什么区别？\nA：关键词搜索是从闲鱼全站搜索商品，店铺搜索是爬取指定店铺的商品。关键词搜索更快但可能触发风控，店铺搜索更慢但更稳定。', keywords='商品获取,PRODUCT_FETCH,关键词,店铺,搜索,targetCount,采集', updated_time=NOW() WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='商品获取节点(PRODUCT_FETCH)详解';

-- 4. 商品筛选节点 PRODUCT_FILTER 详解
INSERT INTO ai_cs_knowledge(tenant_id, category, title, content, keywords, priority, enabled, sort_order, created_time, updated_time)
SELECT NULL, 'workflow_teaching', '商品筛选节点(PRODUCT_FILTER)详解',
'商品筛选节点使用 AI 对采集到的商品进行智能筛选，只保留符合你要求的商品。\n\n配置参数：\n• 是否启用(enabled)：true 开启筛选 / false 关闭筛选。默认工作流中此节点关闭。\n• 筛选规则(screenPrompt)：自然语言描述你的筛选条件。例如"只保留价格大于 50 元的商品"、"排除虚拟商品和二手衣物"、"只要带原图的商品"。\n• 筛选失败处理(onFilterFail)：retry(重新采集) / skip(跳过当前商品继续) / terminate(终止工作流)\n• 最大重试次数(maxRetries)：默认 5，筛选后数量不足时回到商品获取节点重新采集的次数。\n\n工作原理：\n1. AI 会读取每个商品的标题、描述、价格、地区等信息\n2. 根据你的 screenPrompt 判断商品是否符合条件\n3. 符合条件的保留，不符合的过滤掉\n4. 如果筛选后数量不足 targetCount，自动回到商品获取节点重新采集更多商品\n\n筛选规则示例：\n• "只保留价格在 30-200 元之间的商品"\n• "排除虚拟商品、充值卡、Q币"\n• "只要全新商品，不要二手"\n• "优先选择销量高的商品"\n• "排除偏远地区(新疆、西藏、内蒙古)的商品"\n\n常见问题：\nQ：筛选后商品数量不够怎么办？\nA：系统会自动回到商品获取节点重新采集更多商品(最多重试 maxRetries 次)。如果重试后仍不够，会以实际筛选到的数量继续执行。\nQ：筛选规则写不好导致全部被过滤了怎么办？\nA：可以修改 screenPrompt 放宽条件，或直接关闭筛选节点(enabled=false)。\nQ：筛选会消耗 Token 吗？\nA：会的，筛选调用通用 AI 模型按次计费，每筛选一个商品扣一次费用。如果不需要筛选建议关闭以节省 Token。',
'商品筛选,PRODUCT_FILTER,筛选,AI筛选,screenPrompt,过滤', 200, 1, 103, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM ai_cs_knowledge WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='商品筛选节点(PRODUCT_FILTER)详解');

UPDATE ai_cs_knowledge SET content='商品筛选节点使用 AI 对采集到的商品进行智能筛选，只保留符合你要求的商品。\n\n配置参数：\n• 是否启用(enabled)：true 开启筛选 / false 关闭筛选。默认工作流中此节点关闭。\n• 筛选规则(screenPrompt)：自然语言描述你的筛选条件。例如"只保留价格大于 50 元的商品"、"排除虚拟商品和二手衣物"、"只要带原图的商品"。\n• 筛选失败处理(onFilterFail)：retry(重新采集) / skip(跳过当前商品继续) / terminate(终止工作流)\n• 最大重试次数(maxRetries)：默认 5，筛选后数量不足时回到商品获取节点重新采集的次数。\n\n工作原理：\n1. AI 会读取每个商品的标题、描述、价格、地区等信息\n2. 根据你的 screenPrompt 判断商品是否符合条件\n3. 符合条件的保留，不符合的过滤掉\n4. 如果筛选后数量不足 targetCount，自动回到商品获取节点重新采集更多商品\n\n筛选规则示例：\n• "只保留价格在 30-200 元之间的商品"\n• "排除虚拟商品、充值卡、Q币"\n• "只要全新商品，不要二手"\n• "优先选择销量高的商品"\n• "排除偏远地区(新疆、西藏、内蒙古)的商品"\n\n常见问题：\nQ：筛选后商品数量不够怎么办？\nA：系统会自动回到商品获取节点重新采集更多商品(最多重试 maxRetries 次)。如果重试后仍不够，会以实际筛选到的数量继续执行。\nQ：筛选规则写不好导致全部被过滤了怎么办？\nA：可以修改 screenPrompt 放宽条件，或直接关闭筛选节点(enabled=false)。\nQ：筛选会消耗 Token 吗？\nA：会的，筛选调用通用 AI 模型按次计费，每筛选一个商品扣一次费用。如果不需要筛选建议关闭以节省 Token。', keywords='商品筛选,PRODUCT_FILTER,筛选,AI筛选,screenPrompt,过滤', updated_time=NOW() WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='商品筛选节点(PRODUCT_FILTER)详解';

-- 5. 润色文案节点 PRODUCT_POLISH 详解
INSERT INTO ai_cs_knowledge(tenant_id, category, title, content, keywords, priority, enabled, sort_order, created_time, updated_time)
SELECT NULL, 'workflow_teaching', '润色文案节点(PRODUCT_POLISH)详解',
'润色文案节点使用 AI 对商品标题和描述进行改写优化，让文案更吸引买家。\n\n配置参数：\n• 是否启用(enabled)：true 开启 / false 关闭。默认工作流中此节点关闭。\n• 润色风格(style)：口语化(贴近日常对话) / 简洁(精炼表达) / 吸引眼球(营销感强) / 自定义(使用 customPrompt)\n• 自定义提示词(customPrompt)：style=自定义 时使用，描述你希望的润色方向。支持占位符 {{TITLE}}(原标题) 和 {{CONTENT}}(原描述)。\n\n工作原理：\n1. 读取商品的原始标题和描述\n2. 按你选择的风格或自定义提示词调用通用 AI 模型改写\n3. 改写后的文案替换原始文案，用于后续发布\n\n使用建议：\n• 如果采集的商品文案质量已经不错，可以关闭润色以节省 Token。\n• 如果想差异化避免和别人雷同，建议开启润色。\n• 自定义提示词示例："把标题改写成疑问句引发好奇心，描述部分增加使用场景说明，语气要亲切自然像朋友推荐"。\n\n常见问题：\nQ：润色后标题太长怎么办？\nA：闲鱼标题有字数限制，系统会自动截断。建议在 customPrompt 中注明"标题控制在 30 字以内"。\nQ：润色会改变商品价格吗？\nA：不会，润色只改写标题和描述，不修改价格、图片等其他字段。\nQ：润色和筛选有什么区别？\nA：筛选是决定商品要不要(过滤)，润色是优化商品的文案(改写)。筛选在前，润色在后。',
'润色,PRODUCT_POLISH,文案,标题,描述,改写,润色风格', 200, 1, 104, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM ai_cs_knowledge WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='润色文案节点(PRODUCT_POLISH)详解');

UPDATE ai_cs_knowledge SET content='润色文案节点使用 AI 对商品标题和描述进行改写优化，让文案更吸引买家。\n\n配置参数：\n• 是否启用(enabled)：true 开启 / false 关闭。默认工作流中此节点关闭。\n• 润色风格(style)：口语化(贴近日常对话) / 简洁(精炼表达) / 吸引眼球(营销感强) / 自定义(使用 customPrompt)\n• 自定义提示词(customPrompt)：style=自定义 时使用，描述你希望的润色方向。支持占位符 {{TITLE}}(原标题) 和 {{CONTENT}}(原描述)。\n\n工作原理：\n1. 读取商品的原始标题和描述\n2. 按你选择的风格或自定义提示词调用通用 AI 模型改写\n3. 改写后的文案替换原始文案，用于后续发布\n\n使用建议：\n• 如果采集的商品文案质量已经不错，可以关闭润色以节省 Token。\n• 如果想差异化避免和别人雷同，建议开启润色。\n• 自定义提示词示例："把标题改写成疑问句引发好奇心，描述部分增加使用场景说明，语气要亲切自然像朋友推荐"。\n\n常见问题：\nQ：润色后标题太长怎么办？\nA：闲鱼标题有字数限制，系统会自动截断。建议在 customPrompt 中注明"标题控制在 30 字以内"。\nQ：润色会改变商品价格吗？\nA：不会，润色只改写标题和描述，不修改价格、图片等其他字段。\nQ：润色和筛选有什么区别？\nA：筛选是决定商品要不要(过滤)，润色是优化商品的文案(改写)。筛选在前，润色在后。', keywords='润色,PRODUCT_POLISH,文案,标题,描述,改写,润色风格', updated_time=NOW() WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='润色文案节点(PRODUCT_POLISH)详解';

-- 6. 生图节点 IMAGE_GENERATE 详解
INSERT INTO ai_cs_knowledge(tenant_id, category, title, content, keywords, priority, enabled, sort_order, created_time, updated_time)
SELECT NULL, 'workflow_teaching', '生图节点(IMAGE_GENERATE)详解',
'生图节点使用 AI 为每个商品生成封面图，这是发布商品的必要步骤——未生成 AI 封面图的商品严禁发布。\n\n配置参数：\n• 每商品生图数量(imageCount)：默认 1，每个商品生成几张封面图。\n• 图片尺寸(imageSize)：默认 1024x1024(正方形)。\n• 提示词模式(promptMode)：default(自动匹配类目) / custom(自定义提示词)。\n• 自定义提示词(customImagePrompt)：promptMode=custom 时使用。支持占位符 {{TITLE}} 和 {{CONTENT}}。\n• 指定模型(modelKey)：指定使用哪个生图模型。默认工作流使用 image-2 模型。\n• 参考图(referenceImages)：上传 1-9 张参考图，启用图生图模式。不上传则为纯文生图。\n• 并行任务数(parallelCount)：1-5，同时生成几张图，越大越快但可能触发限流。\n\n计费规则：\n• gpt-image-2 模型 1024x1024 规格：12 Token/张\n• 生图是工作流中 Token 消耗最大的环节，请确保余额充足。\n• 余额不足时，已生成的图片仍会继续发布(标记 partial=True)。\n\n重要说明：\n1. imageCount 会自动取 max(配置值, 商品数量)，确保每个商品都有封面图。\n2. 生图完成后会立即发布(内联发布模式)，不需要等发布节点。\n3. 如果生图失败，对应商品会被跳过，不会阻塞其他商品。\n4. 默认提示词会根据商品类目自动生成适合闲鱼/淘宝风格的电商主图，强调不要平台截图、不要水印。\n\n常见问题：\nQ：生图为什么这么慢？\nA：AI 生图本身需要时间(每张约 10-30 秒)，加上闲鱼限流。可以增大 parallelCount 加速，但不要超过 5。\nQ：可以用自己的图片不用 AI 生图吗？\nA：当前工作流必须通过 AI 生图节点生成封面图，这是发布前置条件。如果不想生图可以只采集不发布(发布模式选 draft_only 存草稿)。\nQ：image-2 和 image-3 有什么区别？\nA：image-3 是更新的模型，画质更好但更贵。image-2 性价比更高，适合日常使用。可以在管理端模型配置中启用不同模型。\nQ：参考图有什么用？\nA：上传参考图后为图生图模式，AI 会参考图片风格生成封面图。适合需要统一风格的场景。',
'生图,IMAGE_GENERATE,image-2,封面图,AI生图,图片生成,modelKey', 200, 1, 105, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM ai_cs_knowledge WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='生图节点(IMAGE_GENERATE)详解');

UPDATE ai_cs_knowledge SET content='生图节点使用 AI 为每个商品生成封面图，这是发布商品的必要步骤——未生成 AI 封面图的商品严禁发布。\n\n配置参数：\n• 每商品生图数量(imageCount)：默认 1，每个商品生成几张封面图。\n• 图片尺寸(imageSize)：默认 1024x1024(正方形)。\n• 提示词模式(promptMode)：default(自动匹配类目) / custom(自定义提示词)。\n• 自定义提示词(customImagePrompt)：promptMode=custom 时使用。支持占位符 {{TITLE}} 和 {{CONTENT}}。\n• 指定模型(modelKey)：指定使用哪个生图模型。默认工作流使用 image-2 模型。\n• 参考图(referenceImages)：上传 1-9 张参考图，启用图生图模式。不上传则为纯文生图。\n• 并行任务数(parallelCount)：1-5，同时生成几张图，越大越快但可能触发限流。\n\n计费规则：\n• gpt-image-2 模型 1024x1024 规格：12 Token/张\n• 生图是工作流中 Token 消耗最大的环节，请确保余额充足。\n• 余额不足时，已生成的图片仍会继续发布(标记 partial=True)。\n\n重要说明：\n1. imageCount 会自动取 max(配置值, 商品数量)，确保每个商品都有封面图。\n2. 生图完成后会立即发布(内联发布模式)，不需要等发布节点。\n3. 如果生图失败，对应商品会被跳过，不会阻塞其他商品。\n4. 默认提示词会根据商品类目自动生成适合闲鱼/淘宝风格的电商主图，强调不要平台截图、不要水印。\n\n常见问题：\nQ：生图为什么这么慢？\nA：AI 生图本身需要时间(每张约 10-30 秒)，加上闲鱼限流。可以增大 parallelCount 加速，但不要超过 5。\nQ：可以用自己的图片不用 AI 生图吗？\nA：当前工作流必须通过 AI 生图节点生成封面图，这是发布前置条件。如果不想生图可以只采集不发布(发布模式选 draft_only 存草稿)。\nQ：image-2 和 image-3 有什么区别？\nA：image-3 是更新的模型，画质更好但更贵。image-2 性价比更高，适合日常使用。可以在管理端模型配置中启用不同模型。\nQ：参考图有什么用？\nA：上传参考图后为图生图模式，AI 会参考图片风格生成封面图。适合需要统一风格的场景。', keywords='生图,IMAGE_GENERATE,image-2,封面图,AI生图,图片生成,modelKey', updated_time=NOW() WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='生图节点(IMAGE_GENERATE)详解';

-- 7. 发布节点 PUBLISH 详解
INSERT INTO ai_cs_knowledge(tenant_id, category, title, content, keywords, priority, enabled, sort_order, created_time, updated_time)
SELECT NULL, 'workflow_teaching', '发布节点(PUBLISH)详解',
'发布节点负责将商品发布到闲鱼账号。在当前架构中，生图节点完成后会立即发布(内联发布)，发布节点变为汇总节点，统计发布结果。\n\n配置参数：\n• 发布间隔(publishIntervalSeconds)：默认 30 秒，同一账号两次发布之间的间隔，避免触发闲鱼限流。\n• 发布分类(category)：指定商品发布的类目。\n• 地址(address)：发布地址，影响商品展示的地区。\n• 价格策略(priceStrategy)：keep(保留原价) / 其他策略。\n\n两种发布模式(publishMode)：\n1. publish(直接发布)：生图后直接发布到闲鱼，商品立即可见。\n2. draft_only(仅存草稿)：生图后存入草稿箱，不实际发布。可以在草稿箱中预览、编辑、手动发布。\n\n发布前校验(强制)：\n1. 必须有 AI 生成的封面图(img_ai_ok=True)，否则阻止发布。\n2. 商品标题和描述不能为空，否则阻止发布。\n3. 重复发布会自动跳过(去重机制)。\n\n账号类型差异：\n• 鱼小铺账号：可自定义库存数量。\n• 普通账号：库存固定为 1。\n\n草稿箱功能：\n• publishMode=draft_only 时，所有商品存入草稿箱(status=draft)。\n• 草稿箱支持单条重试发布和批量重试发布。\n• 草稿箱有去重索引(tenant_id + account_id + source_item_id + source_title_hash)，避免重复发布。\n\n常见问题：\nQ：发布失败怎么办？\nA：查看执行日志中的错误信息。常见原因：Cookie 失效、网络超时、闲鱼限流、商品信息不完整。失败的记录可在草稿箱重试。\nQ：为什么发布间隔要 30 秒？\nA：闲鱼对发布频率有限制，过快会触发限流甚至封号。30 秒是安全间隔，不建议调低。\nQ：直接发布和存草稿有什么区别？\nA：直接发布立即可见但无法预览；存草稿可以先预览确认再发布，更安全。新手建议先用 draft_only 模式。',
'发布,PUBLISH,发布节点,草稿箱,draft_only,publishMode,发布间隔', 200, 1, 106, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM ai_cs_knowledge WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='发布节点(PUBLISH)详解');

UPDATE ai_cs_knowledge SET content='发布节点负责将商品发布到闲鱼账号。在当前架构中，生图节点完成后会立即发布(内联发布)，发布节点变为汇总节点，统计发布结果。\n\n配置参数：\n• 发布间隔(publishIntervalSeconds)：默认 30 秒，同一账号两次发布之间的间隔，避免触发闲鱼限流。\n• 发布分类(category)：指定商品发布的类目。\n• 地址(address)：发布地址，影响商品展示的地区。\n• 价格策略(priceStrategy)：keep(保留原价) / 其他策略。\n\n两种发布模式(publishMode)：\n1. publish(直接发布)：生图后直接发布到闲鱼，商品立即可见。\n2. draft_only(仅存草稿)：生图后存入草稿箱，不实际发布。可以在草稿箱中预览、编辑、手动发布。\n\n发布前校验(强制)：\n1. 必须有 AI 生成的封面图(img_ai_ok=True)，否则阻止发布。\n2. 商品标题和描述不能为空，否则阻止发布。\n3. 重复发布会自动跳过(去重机制)。\n\n账号类型差异：\n• 鱼小铺账号：可自定义库存数量。\n• 普通账号：库存固定为 1。\n\n草稿箱功能：\n• publishMode=draft_only 时，所有商品存入草稿箱(status=draft)。\n• 草稿箱支持单条重试发布和批量重试发布。\n• 草稿箱有去重索引(tenant_id + account_id + source_item_id + source_title_hash)，避免重复发布。\n\n常见问题：\nQ：发布失败怎么办？\nA：查看执行日志中的错误信息。常见原因：Cookie 失效、网络超时、闲鱼限流、商品信息不完整。失败的记录可在草稿箱重试。\nQ：为什么发布间隔要 30 秒？\nA：闲鱼对发布频率有限制，过快会触发限流甚至封号。30 秒是安全间隔，不建议调低。\nQ：直接发布和存草稿有什么区别？\nA：直接发布立即可见但无法预览；存草稿可以先预览确认再发布，更安全。新手建议先用 draft_only 模式。', keywords='发布,PUBLISH,发布节点,草稿箱,draft_only,publishMode,发布间隔', updated_time=NOW() WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='发布节点(PUBLISH)详解';

-- 8. 商品数量与账号关系（核心公式）
INSERT INTO ai_cs_knowledge(tenant_id, category, title, content, keywords, priority, enabled, sort_order, created_time, updated_time)
SELECT NULL, 'workflow_teaching', '商品数量与账号关系核心公式',
'工作流中最核心的公式：商品数量 × 账号数量 = 最终实际发布商品数量。\n\n详细解释：\n• 商品数量(targetCount)：在商品获取节点配置，表示每个账号要采集多少个商品。\n• 账号数量：在触发器节点选择的发布账号数量。\n• 最终发布数量 = targetCount × 账号数量。\n\n举例：\n• targetCount=5，选 1 个账号 → 采集 5 个商品，发布 5 个商品。\n• targetCount=5，选 2 个账号 → 每个账号采集 5 个，共采集 10 个，发布 10 个商品。\n• targetCount=10，选 3 个账号 → 每个账号采集 10 个，共采集 30 个，发布 30 个商品。\n\nToken 消耗估算：\n• 生图是主要消耗：每张图 12 Token(image-2, 1024x1024)。\n• 总生图 Token = 最终发布数量 × 12。\n• 例如 targetCount=5 + 2 个账号 = 10 个商品 × 12 = 120 Token。\n• 如果开启了筛选，每个商品筛选约 3 Token(通用模型按次计费)。\n• 如果开启了润色，每个商品润色约 3 Token。\n\n重要提醒：\n1. 请确保 Token 余额充足再运行，否则中途余额不足会中断(已生成的图片仍会发布)。\n2. targetCount 不要设太大，建议从 5 开始逐步增加。\n3. 多账号会成倍增加采集和发布量，请量力而行。\n4. 如果闲鱼搜索结果不足 targetCount，实际采集数量可能少于配置值。',
'商品数量,账号数量,公式,发布数量,targetCount,Token消耗', 210, 1, 107, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM ai_cs_knowledge WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='商品数量与账号关系核心公式');

UPDATE ai_cs_knowledge SET content='工作流中最核心的公式：商品数量 × 账号数量 = 最终实际发布商品数量。\n\n详细解释：\n• 商品数量(targetCount)：在商品获取节点配置，表示每个账号要采集多少个商品。\n• 账号数量：在触发器节点选择的发布账号数量。\n• 最终发布数量 = targetCount × 账号数量。\n\n举例：\n• targetCount=5，选 1 个账号 → 采集 5 个商品，发布 5 个商品。\n• targetCount=5，选 2 个账号 → 每个账号采集 5 个，共采集 10 个，发布 10 个商品。\n• targetCount=10，选 3 个账号 → 每个账号采集 10 个，共采集 30 个，发布 30 个商品。\n\nToken 消耗估算：\n• 生图是主要消耗：每张图 12 Token(image-2, 1024x1024)。\n• 总生图 Token = 最终发布数量 × 12。\n• 例如 targetCount=5 + 2 个账号 = 10 个商品 × 12 = 120 Token。\n• 如果开启了筛选，每个商品筛选约 3 Token(通用模型按次计费)。\n• 如果开启了润色，每个商品润色约 3 Token。\n\n重要提醒：\n1. 请确保 Token 余额充足再运行，否则中途余额不足会中断(已生成的图片仍会发布)。\n2. targetCount 不要设太大，建议从 5 开始逐步增加。\n3. 多账号会成倍增加采集和发布量，请量力而行。\n4. 如果闲鱼搜索结果不足 targetCount，实际采集数量可能少于配置值。', keywords='商品数量,账号数量,公式,发布数量,targetCount,Token消耗', updated_time=NOW() WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='商品数量与账号关系核心公式';

-- 9. 工作流执行与发布模式
INSERT INTO ai_cs_knowledge(tenant_id, category, title, content, keywords, priority, enabled, sort_order, created_time, updated_time)
SELECT NULL, 'workflow_teaching', '工作流执行流程与发布模式',
'工作流执行是异步的：点击运行后立即返回，后台异步执行，前端轮询更新进度。\n\n执行流程：\n1. Java 网关校验工作流 DAG、账号登录状态、发布地址。\n2. 创建执行记录(execution_no)，状态=running。\n3. 异步调用 Python 执行引擎，按拓扑顺序执行各节点。\n4. 每个节点执行后更新进度、写入时间线(timeline)和节点日志(node_log)。\n5. 全部完成后更新执行记录状态(success/failed)。\n\n节点执行顺序(拓扑排序)：\n触发器 → 商品获取 → 商品筛选 → 润色文案 → 生图(内联发布) → 发布(汇总)\n\n重试机制：\n• 如果商品筛选后数量不足，自动回到商品获取节点重新采集(最多 5 次)。\n• 如果某节点执行失败，可以在执行记录中点击"重试失败节点"。\n• "继续执行"功能：复用已生成的图片，从失败节点继续，不重新生图。\n\n发布模式(publishMode)：\n• publish(直接发布，默认)：生图后立即发布到闲鱼。\n• draft_only(仅存草稿)：生图后存入草稿箱，不实际发布。\n• 运行前会弹窗让你选择发布模式。\n\n执行记录查看：\n• 在工作流详情页的"执行记录"tab 查看历史执行。\n• 点击执行记录可查看时间线、节点日志、产物(artifact)。\n• 时间线展示每个节点的开始、完成、错误事件。\n\n常见问题：\nQ：工作流执行中可以终止吗？\nA：可以，在执行记录中点击"终止"按钮。已发布的商品不会撤回。\nQ：执行失败后怎么恢复？\nA：三种方式：(1)重试失败节点 (2)继续执行(复用已生成的图) (3)草稿箱重试发布。\nQ：为什么执行记录显示成功但没有发布商品？\nA：可能是 publishMode=draft_only(存草稿)，或所有商品都被去重跳过了。检查草稿箱和执行日志。',
'执行,发布模式,publish,draft_only,重试,继续执行,执行记录,时间线', 200, 1, 108, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM ai_cs_knowledge WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='工作流执行流程与发布模式');

UPDATE ai_cs_knowledge SET content='工作流执行是异步的：点击运行后立即返回，后台异步执行，前端轮询更新进度。\n\n执行流程：\n1. Java 网关校验工作流 DAG、账号登录状态、发布地址。\n2. 创建执行记录(execution_no)，状态=running。\n3. 异步调用 Python 执行引擎，按拓扑顺序执行各节点。\n4. 每个节点执行后更新进度、写入时间线(timeline)和节点日志(node_log)。\n5. 全部完成后更新执行记录状态(success/failed)。\n\n节点执行顺序(拓扑排序)：\n触发器 → 商品获取 → 商品筛选 → 润色文案 → 生图(内联发布) → 发布(汇总)\n\n重试机制：\n• 如果商品筛选后数量不足，自动回到商品获取节点重新采集(最多 5 次)。\n• 如果某节点执行失败，可以在执行记录中点击"重试失败节点"。\n• "继续执行"功能：复用已生成的图片，从失败节点继续，不重新生图。\n\n发布模式(publishMode)：\n• publish(直接发布，默认)：生图后立即发布到闲鱼。\n• draft_only(仅存草稿)：生图后存入草稿箱，不实际发布。\n• 运行前会弹窗让你选择发布模式。\n\n执行记录查看：\n• 在工作流详情页的"执行记录"tab 查看历史执行。\n• 点击执行记录可查看时间线、节点日志、产物(artifact)。\n• 时间线展示每个节点的开始、完成、错误事件。\n\n常见问题：\nQ：工作流执行中可以终止吗？\nA：可以，在执行记录中点击"终止"按钮。已发布的商品不会撤回。\nQ：执行失败后怎么恢复？\nA：三种方式：(1)重试失败节点 (2)继续执行(复用已生成的图) (3)草稿箱重试发布。\nQ：为什么执行记录显示成功但没有发布商品？\nA：可能是 publishMode=draft_only(存草稿)，或所有商品都被去重跳过了。检查草稿箱和执行日志。', keywords='执行,发布模式,publish,draft_only,重试,继续执行,执行记录,时间线', updated_time=NOW() WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='工作流执行流程与发布模式';

-- 10. 常见刁钻问题与解答
INSERT INTO ai_cs_knowledge(tenant_id, category, title, content, keywords, priority, enabled, sort_order, created_time, updated_time)
SELECT NULL, 'workflow_teaching', '工作流常见刁钻问题与解答',
'Q：工作流和自动回复有什么区别？\nA：自动回复是单条消息响应——买家发消息时触发一次回复。工作流是多步骤流程——从采集商品到生图到发布全自动。两者完全独立，互不影响。\n\nQ：工作流可以定时执行吗？\nA：工作流本身是手动触发的。如果需要定时执行，可以配合定时任务功能，但当前版本工作流暂不支持定时触发，需要手动点击运行。\n\nQ：多个账号会采集到相同的商品吗？\nA：会的。每个账号独立采集，可能采集到相同商品。但发布时有去重机制(基于 source_item_id + title_hash)，同一账号不会重复发布相同商品。不同账号可以发布相同商品。\n\nQ：可以只采集不生图不发布吗？\nA：当前工作流架构中，生图是发布的必要前置条件。如果只想采集，可以把发布模式选为 draft_only(存草稿)，但生图节点仍会执行。如果完全不想生图，建议使用商机发掘功能而非工作流。\n\nQ：工作流执行到一半 Token 用完了怎么办？\nA：已生成的图片会继续发布(标记 partial=True)，未生图的商品会被跳过。充值 Token 后可以用"继续执行"功能从失败节点恢复，复用已生成的图。\n\nQ：为什么我的商品发布后被闲鱼下架了？\nA：可能原因：(1)商品信息违规(2)发布频率过快触发风控(3)账号被限制。建议：发布间隔保持 30 秒以上，商品文案不要含违规词，使用 AI 生成的封面图。\n\nQ：可以同时运行多个工作流吗？\nA：可以创建多个工作流，但不建议同时运行多个，因为会共享账号和 Token 资源，可能互相影响。建议一个执行完再运行下一个。\n\nQ：工作流的草稿箱在哪里？\nA：在工作流页面的"草稿箱"tab。publishMode=draft_only 的商品会存入草稿箱，支持单条/批量重试发布。\n\nQ：修改了工作流配置，之前发布的商品会受影响吗？\nA：不会。已发布的商品是独立的，修改工作流只影响后续执行。工作流支持版本管理，发布后会创建版本快照，可以回滚到之前的版本。\n\nQ：为什么生图节点要用 image-2 而不是 image-3？\nA：image-2 性价比更高(12 Token/张)，画质足够日常使用。image-3 画质更好但更贵。默认工作流使用 image-2 是为了平衡成本和效果，你可以在节点配置中切换 modelKey。\n\nQ：工作流执行日志在哪里看？\nA：工作流详情页 → 执行记录 tab → 点击执行记录 → 查看时间线和节点日志。节点日志包含输入、输出、耗时、AI 请求摘要、发布参数摘要等详细信息。',
'刁钻问题,常见问题,FAQ,工作流,区别,定时,下架,草稿箱', 210, 1, 109, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM ai_cs_knowledge WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='工作流常见刁钻问题与解答');

UPDATE ai_cs_knowledge SET content='Q：工作流和自动回复有什么区别？\nA：自动回复是单条消息响应——买家发消息时触发一次回复。工作流是多步骤流程——从采集商品到生图到发布全自动。两者完全独立，互不影响。\n\nQ：工作流可以定时执行吗？\nA：工作流本身是手动触发的。如果需要定时执行，可以配合定时任务功能，但当前版本工作流暂不支持定时触发，需要手动点击运行。\n\nQ：多个账号会采集到相同的商品吗？\nA：会的。每个账号独立采集，可能采集到相同商品。但发布时有去重机制(基于 source_item_id + title_hash)，同一账号不会重复发布相同商品。不同账号可以发布相同商品。\n\nQ：可以只采集不生图不发布吗？\nA：当前工作流架构中，生图是发布的必要前置条件。如果只想采集，可以把发布模式选为 draft_only(存草稿)，但生图节点仍会执行。如果完全不想生图，建议使用商机发掘功能而非工作流。\n\nQ：工作流执行到一半 Token 用完了怎么办？\nA：已生成的图片会继续发布(标记 partial=True)，未生图的商品会被跳过。充值 Token 后可以用"继续执行"功能从失败节点恢复，复用已生成的图。\n\nQ：为什么我的商品发布后被闲鱼下架了？\nA：可能原因：(1)商品信息违规(2)发布频率过快触发风控(3)账号被限制。建议：发布间隔保持 30 秒以上，商品文案不要含违规词，使用 AI 生成的封面图。\n\nQ：可以同时运行多个工作流吗？\nA：可以创建多个工作流，但不建议同时运行多个，因为会共享账号和 Token 资源，可能互相影响。建议一个执行完再运行下一个。\n\nQ：工作流的草稿箱在哪里？\nA：在工作流页面的"草稿箱"tab。publishMode=draft_only 的商品会存入草稿箱，支持单条/批量重试发布。\n\nQ：修改了工作流配置，之前发布的商品会受影响吗？\nA：不会。已发布的商品是独立的，修改工作流只影响后续执行。工作流支持版本管理，发布后会创建版本快照，可以回滚到之前的版本。\n\nQ：为什么生图节点要用 image-2 而不是 image-3？\nA：image-2 性价比更高(12 Token/张)，画质足够日常使用。image-3 画质更好但更贵。默认工作流使用 image-2 是为了平衡成本和效果，你可以在节点配置中切换 modelKey。\n\nQ：工作流执行日志在哪里看？\nA：工作流详情页 → 执行记录 tab → 点击执行记录 → 查看时间线和节点日志。节点日志包含输入、输出、耗时、AI 请求摘要、发布参数摘要等详细信息。', keywords='刁钻问题,常见问题,FAQ,工作流,区别,定时,下架,草稿箱', updated_time=NOW() WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='工作流常见刁钻问题与解答';

-- 11. 新建工作流与节点配置指南
INSERT INTO ai_cs_knowledge(tenant_id, category, title, content, keywords, priority, enabled, sort_order, created_time, updated_time)
SELECT NULL, 'workflow_teaching', '新建工作流与节点配置指南',
'如何新建工作流：\n1. 在工作流页面点击"新建工作流"按钮。\n2. 系统会自动生成一个包含 6 个节点的模板：触发器→商品获取→商品筛选→润色文案→生图→发布。\n3. 你可以修改每个节点的配置，也可以删除不需要的节点。\n4. 配置完成后点击"保存"，然后"发布"工作流(发布后会创建版本快照)。\n5. 点击"运行"按钮执行工作流。\n\n节点配置建议：\n\n【最小化工作流】(只采集发布)：\n• 触发器：选 1 个账号\n• 商品获取：关键词搜索，targetCount=5\n• 商品筛选：关闭(enabled=false)\n• 润色文案：关闭(enabled=false)\n• 生图：image-2，imageCount=1\n• 发布：默认配置\n\n【精细化工作流】(筛选+润色)：\n• 触发器：选 1-2 个账号\n• 商品获取：关键词搜索，targetCount=10\n• 商品筛选：开启，screenPrompt="只要全新商品，价格 30-200 元，排除虚拟物品"\n• 润色文案：开启，style=吸引眼球\n• 生图：image-2，imageCount=1\n• 发布：默认配置\n\n【店铺搬运工作流】：\n• 触发器：选账号\n• 商品获取：店铺搜索(shopUrl=竞品店铺链接)，targetCount=20\n• 商品筛选：开启，screenPrompt="排除低价引流款(价格<10元)"\n• 润色文案：开启，style=自定义，customPrompt="把标题改成自己的风格，描述增加使用感受"\n• 生图：image-2\n• 发布：默认配置\n\n节点连线规则：\n• 每个工作流必须有且仅有一个触发器节点。\n• 节点之间通过连线串联，数据从上游流向下游。\n• 商品筛选节点支持 RETRY 路由：筛选后数量不足会自动回到商品获取节点。\n• 删除节点会同时删除关联的连线。\n\n常见问题：\nQ：可以跳过某些节点吗？\nA：可以关闭节点(enabled=false)或直接删除节点。但生图节点不能跳过(发布前置条件)。\nQ：节点顺序可以调换吗？\nA：可以拖拽节点调整位置和连线。但逻辑顺序必须是：触发器→获取→筛选→润色→生图→发布。\nQ：保存和发布有什么区别？\nA：保存只是暂存修改，发布会创建版本快照并使工作流可执行。修改后需要重新发布才能生效。',
'新建工作流,节点配置,模板,连线,保存,发布,配置指南', 200, 1, 110, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM ai_cs_knowledge WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='新建工作流与节点配置指南');

UPDATE ai_cs_knowledge SET content='如何新建工作流：\n1. 在工作流页面点击"新建工作流"按钮。\n2. 系统会自动生成一个包含 6 个节点的模板：触发器→商品获取→商品筛选→润色文案→生图→发布。\n3. 你可以修改每个节点的配置，也可以删除不需要的节点。\n4. 配置完成后点击"保存"，然后"发布"工作流(发布后会创建版本快照)。\n5. 点击"运行"按钮执行工作流。\n\n节点配置建议：\n\n【最小化工作流】(只采集发布)：\n• 触发器：选 1 个账号\n• 商品获取：关键词搜索，targetCount=5\n• 商品筛选：关闭(enabled=false)\n• 润色文案：关闭(enabled=false)\n• 生图：image-2，imageCount=1\n• 发布：默认配置\n\n【精细化工作流】(筛选+润色)：\n• 触发器：选 1-2 个账号\n• 商品获取：关键词搜索，targetCount=10\n• 商品筛选：开启，screenPrompt="只要全新商品，价格 30-200 元，排除虚拟物品"\n• 润色文案：开启，style=吸引眼球\n• 生图：image-2，imageCount=1\n• 发布：默认配置\n\n【店铺搬运工作流】：\n• 触发器：选账号\n• 商品获取：店铺搜索(shopUrl=竞品店铺链接)，targetCount=20\n• 商品筛选：开启，screenPrompt="排除低价引流款(价格<10元)"\n• 润色文案：开启，style=自定义，customPrompt="把标题改成自己的风格，描述增加使用感受"\n• 生图：image-2\n• 发布：默认配置\n\n节点连线规则：\n• 每个工作流必须有且仅有一个触发器节点。\n• 节点之间通过连线串联，数据从上游流向下游。\n• 商品筛选节点支持 RETRY 路由：筛选后数量不足会自动回到商品获取节点。\n• 删除节点会同时删除关联的连线。\n\n常见问题：\nQ：可以跳过某些节点吗？\nA：可以关闭节点(enabled=false)或直接删除节点。但生图节点不能跳过(发布前置条件)。\nQ：节点顺序可以调换吗？\nA：可以拖拽节点调整位置和连线。但逻辑顺序必须是：触发器→获取→筛选→润色→生图→发布。\nQ：保存和发布有什么区别？\nA：保存只是暂存修改，发布会创建版本快照并使工作流可执行。修改后需要重新发布才能生效。', keywords='新建工作流,节点配置,模板,连线,保存,发布,配置指南', updated_time=NOW() WHERE tenant_id IS NULL AND category='workflow_teaching' AND title='新建工作流与节点配置指南';
