-- V1.12: 工作流商品草稿箱表（与 workflow_definition 等表同库）
-- 用途：工作流 PUBLISH 节点发布前先存草稿，无论发布成功或失败都保留记录
CREATE TABLE IF NOT EXISTS workflow_goods_draft (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  user_id BIGINT NULL COMMENT '用户ID',
  workflow_id BIGINT NULL COMMENT '工作流定义ID',
  workflow_execution_id BIGINT NULL COMMENT '工作流执行记录ID',
  workflow_name VARCHAR(200) NULL COMMENT '工作流名称（冗余存储）',
  node_key VARCHAR(100) NULL COMMENT '产生该商品的节点key',
  account_id BIGINT NULL COMMENT '闲鱼账号ID',
  title VARCHAR(500) NOT NULL COMMENT '商品标题',
  price VARCHAR(50) NULL COMMENT '商品价格',
  description TEXT NULL COMMENT '商品描述',
  cover_pic TEXT NULL COMMENT '封面图URL',
  image_urls JSON NULL COMMENT '图片URL列表',
  category VARCHAR(100) NULL COMMENT '分类',
  stock INT DEFAULT 1 COMMENT '库存',
  location JSON NULL COMMENT '发货地',
  raw_payload JSON NULL COMMENT '原始商品数据快照',
  source_item_id VARCHAR(100) NULL COMMENT '源商品ID（去重用）',
  source_title_hash VARCHAR(64) NULL COMMENT '源标题hash（去重用）',
  publish_status VARCHAR(20) NOT NULL DEFAULT 'draft' COMMENT 'draft/publishing/published/failed',
  publish_time DATETIME NULL COMMENT '发布时间',
  xianyu_goods_id VARCHAR(100) NULL COMMENT '闲鱼返回的商品ID',
  publish_error_message TEXT NULL COMMENT '发布失败错误信息',
  publish_attempt_count INT DEFAULT 0 COMMENT '发布尝试次数',
  created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_wgd_tenant_status_created (tenant_id, publish_status, created_time DESC),
  INDEX idx_wgd_workflow_execution (workflow_execution_id),
  INDEX idx_wgd_tenant_deleted (tenant_id, deleted),
  INDEX idx_wgd_dedup (tenant_id, account_id, source_item_id, source_title_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工作流商品草稿箱';
